// anotame-web/src/routes/(app)/dashboard/admin/users/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiService, API_IDENTITY } from '$lib/services/api.svelte';
  import { Button } from '$lib/components/ui/button';
  import { Edit, Trash2 } from 'lucide-svelte';
  import { adaptiveConfirm } from '$lib/components/ui/responsive/confirm-state.svelte';
  import { toast } from 'svelte-sonner';
  import DataTableWrapper from '$lib/components/ui/DataTableWrapper.svelte';
  import type { ColumnDef } from '@tanstack/table-core';
  import * as m from '$lib/paraglide/messages';

  import UserDialog from '$lib/components/users/user-dialog.svelte';

  let users = $state<any[]>([]);
  let loading = $state(true);

  // Single dialog state
  let editingUser = $state<any | null>(null);

  const columns: ColumnDef<any>[] = [
    { id: 'nombre', accessorFn: (row) => `${row.firstName} ${row.lastName}`, header: 'Nombre', enableSorting: true },
    { accessorKey: 'username', header: 'Usuario', enableSorting: true },
    { accessorKey: 'email', header: 'Email', enableSorting: false },
    { id: 'role', accessorFn: (row) => row.role, header: 'Rol', enableSorting: true },
    { id: 'actions', header: m['common.actions'](), enableSorting: false },
  ];

  async function fetchUsers() {
    loading = true;
    try {
      const data = await apiService.request<any[]>(`${API_IDENTITY}/users`);
      users = data || [];
    } catch (e: any) {
      console.error('Failed to fetch users', e);
      toast.error(m['users.load.error']());
      users = [];
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchUsers();
  });

  function handleCreateClick() {
    editingUser = { isNew: true };
  }

  function handleEditClick(user: any) {
    editingUser = user;
  }

  async function handleDeleteClick(user: any) {
    const ok = await adaptiveConfirm({
      title: m['users.delete.title'](),
      description: m['users.delete.desc']({ username: user.username })
    });
    if (ok) {
      try {
        await apiService.request(`${API_IDENTITY}/users/${user.id}`, { method: 'DELETE' });
        toast.success(m['users.delete.success']());
        users = users.filter(u => u.id !== user.id);
      } catch (e: any) {
        toast.error(e.message || m['users.delete.error']());
      }
    }
  }

  function handleFormSuccess() {
    editingUser = null;
    fetchUsers();
  }
</script>

<div class="space-y-6 animate-in fade-in duration-300">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div>
        <h1 class="text-3xl font-heading font-bold text-foreground">{m['nav.users.name']()}</h1>
        <p class="text-muted-foreground">{m['users.page.desc']()}</p>
      </div>
      <Button onclick={handleCreateClick} class="w-full sm:w-auto h-12 shadow-sm touch-manipulation">
        {m['users.button.new']()}
      </Button>
    </div>

  <div class="bg-card border border-border rounded-xl overflow-hidden shadow-sm p-4">
    <DataTableWrapper
      {columns}
      data={users}
      {loading}
      emptyMessage={m['common.noData']()}
      filterPlaceholder={m['common.searchEllipsis']()}
    >
      {#snippet actionCell(row)}
        <div class="flex justify-end gap-2">
          <Button
            variant="outline"
            size="sm"
            class="h-10 px-4 touch-manipulation font-medium"
            onclick={() => handleEditClick(row.original)}
          >
            <Edit class="w-4 h-4 mr-2" />
            {m['common.edit']()}
          </Button>
          <Button
            variant="outline"
            size="sm"
            class="h-10 px-4 text-destructive hover:text-destructive/90 touch-manipulation font-medium"
            onclick={() => handleDeleteClick(row.original)}
          >
            <Trash2 class="w-4 h-4 mr-2" />
            {m['common.delete']()}
          </Button>
        </div>
      {/snippet}
    </DataTableWrapper>
  </div>

  <UserDialog
    item={editingUser}
    id="user-admin"
    onClose={() => editingUser = null}
    onSuccess={handleFormSuccess}
  />
</div>

// anotame-web/src/app/dashboard/users/page.tsx
"use client";

import { useEffect, useState } from "react";
import { API_IDENTITY } from "@/lib/api";
import { User } from "@/types/auth";
import { useAuth } from "@/context/AuthContext";

export default function UsersPage() {
  const [users, setUsers] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { user: currentUser } = useAuth();

  const fetchUsers = async () => {
    try {
      const res = await fetch(`${API_IDENTITY}/users`);
      if (res.ok) {
        const data = await res.json();
        setUsers(data);
      }
    } catch (err) {
      console.error("Failed to fetch users", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this user?")) return;
    try {
        const res = await fetch(`${API_IDENTITY}/users/${id}`, {
            method: 'DELETE'
        });
        if (res.ok) {
            setUsers(users.filter(u => u.id !== id));
        } else {
            alert("Failed to delete user");
        }
    } catch (err) {
        console.error("Error deleting user", err);
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-heading font-bold text-foreground">
          Users
        </h1>
        <p className="text-muted-foreground">
          Manage system users and access.
        </p>
      </div>

      <div className="bg-card border border-border rounded-xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-muted/50 text-muted-foreground font-medium uppercase text-xs">
              <tr>
                <th className="px-6 py-3">Name</th>
                <th className="px-6 py-3">Username</th>
                <th className="px-6 py-3">Email</th>
                <th className="px-6 py-3">Role</th>
                <th className="px-6 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {isLoading ? (
                <tr><td colSpan={5} className="px-6 py-8 text-center text-muted-foreground">Loading...</td></tr>
              ) : users.length === 0 ? (
                <tr><td colSpan={5} className="px-6 py-8 text-center text-muted-foreground">No users found.</td></tr>
              ) : (
                users.map((u) => (
                  <tr key={u.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-4 font-medium text-foreground">{u.firstName} {u.lastName}</td>
                    <td className="px-6 py-4">{u.username}</td>
                    <td className="px-6 py-4">{u.email}</td>
                    <td className="px-6 py-4">{u.role}</td>
                    <td className="px-6 py-4 text-right">
                        <button 
                            onClick={() => handleDelete(u.id)}
                            className="text-red-600 hover:text-red-800 text-xs font-semibold px-3 py-1 bg-red-50 hover:bg-red-100 rounded-md transition-colors"
                        >
                            Delete
                        </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
