// anotame-web/src/routes/(app)/dashboard/customers/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiService, API_SALES } from '$lib/services/api.svelte';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import * as Table from '$lib/components/ui/table';

  // We will scaffold CustomerDialog incorporating superForms
  import CustomerDialog from '$lib/components/customers/customer-dialog.svelte';

  let customers = $state<any[]>([]);
  let loading = $state(true);
  let searchQuery = $state('');

  // Single Dialog Pattern state
  let editingCustomer = $state<any | null>(null);

  async function fetchCustomers(query: string = '') {
    loading = true;
    try {
      const q = query ? `?query=${query}` : '';
      const response = await apiService.request<any[]>(`${API_SALES}/api/customers/search${q}`);
      customers = response || [];
    } catch {
      customers = [];
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchCustomers();
  });

  function handleSearch(e: Event) {
    e.preventDefault();
    fetchCustomers(searchQuery);
  }

  function handleCreateClick() {
    editingCustomer = { id: null, firstName: '', lastName: '', email: '', phoneNumber: '' };
  }

  function handleEditClick(customer: any) {
    editingCustomer = customer;
  }

  async function handleDeleteClick(id: string) {
    if (confirm("¿Seguro que deseas eliminar este cliente?")) {
      try {
        await apiService.request(`${API_SALES}/api/customers/${id}`, { method: 'DELETE' });
        fetchCustomers(searchQuery);
      } catch (e) {
        alert("Error al eliminar cliente");
      }
    }
  }

  function handleFormSuccess() {
    editingCustomer = null;
    fetchCustomers(searchQuery);
  }
</script>

<div class="space-y-6">
  <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
    <div>
      <h1 class="text-3xl font-heading font-bold text-foreground">Clientes</h1>
      <p class="text-muted-foreground">Gestionar base de datos de clientes.</p>
    </div>
    <Button onclick={handleCreateClick} class="w-full sm:w-auto h-12 touch-manipulation">+ Nuevo Cliente</Button>
  </div>

  <div class="flex gap-2">
    <form onsubmit={handleSearch} class="flex-1 flex gap-2">
      <Input
        placeholder="Buscar clientes..."
        bind:value={searchQuery}
        class="max-w-md h-12"
      />
      <Button type="submit" variant="secondary" class="h-12 px-6">Buscar</Button>
    </form>
  </div>

  <div class="bg-card border border-border rounded-xl overflow-x-auto shadow-sm">
    <Table.Root class="w-full min-w-[600px]">
      <Table.Header>
        <Table.Row>
          <Table.Head class="px-6 py-4">Nombre</Table.Head>
          <Table.Head class="px-6 py-4">Teléfono</Table.Head>
          <Table.Head class="px-6 py-4">Correo</Table.Head>
          <Table.Head class="px-6 py-4 text-right">Acciones</Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#if loading}
          <Table.Row>
            <Table.Cell colspan={4} class="h-24 text-center">
              Cargando...
            </Table.Cell>
          </Table.Row>
        {:else if customers.length === 0}
          <Table.Row>
            <Table.Cell colspan={4} class="h-24 text-center text-muted-foreground">
              No se encontraron clientes.
            </Table.Cell>
          </Table.Row>
        {:else}
          {#each customers as c (c.id)}
            <Table.Row>
              <Table.Cell class="px-6 py-4 font-medium">
                {c.firstName} {c.lastName}
              </Table.Cell>
              <Table.Cell class="px-6 py-4">{c.phoneNumber}</Table.Cell>
              <Table.Cell class="px-6 py-4 text-muted-foreground">{c.email || "-"}</Table.Cell>
              <Table.Cell class="px-6 py-4 text-right space-x-2">
                <Button
                  variant="outline"
                  size="sm"
                  class="h-10 px-4 touch-manipulation"
                  onclick={() => handleEditClick(c)}
                >
                  Editar
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  class="h-10 px-4 text-destructive hover:text-destructive/90 touch-manipulation"
                  onclick={() => c.id && handleDeleteClick(c.id)}
                >
                  Eliminar
                </Button>
              </Table.Cell>
            </Table.Row>
          {/each}
        {/if}
      </Table.Body>
    </Table.Root>
  </div>

  <!-- Single Dialog Page-level Instance -->
  <CustomerDialog item={editingCustomer} onClose={() => editingCustomer = null} onSuccess={handleFormSuccess} />
</div>

// anotame-web/src/app/dashboard/customers/page.tsx
"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { CustomerForm } from "@/components/customers/CustomerForm";
import { searchCustomers, deleteCustomer } from "@/services/sales/customers";
import { CustomerDto } from "@/types/dtos";

export default function CustomersPage() {
  const router = useRouter();
  const [customers, setCustomers] = useState<CustomerDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<CustomerDto | undefined>(undefined);

  const fetchCustomers = useCallback(async (query: string = "") => {
    setLoading(true);
    const results = await searchCustomers(query);
    setCustomers(results);
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchCustomers();
  }, [fetchCustomers]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    fetchCustomers(searchQuery);
  };

  const handleCreateClick = () => {
    router.push("/dashboard/customers/new");
  };

  const handleEditClick = (customer: CustomerDto) => {
    setEditingCustomer(customer);
    setIsModalOpen(true);
  };

  const handleDeleteClick = async (id: string) => {
    if (confirm("Are you sure you want to delete this customer?")) {
      const success = await deleteCustomer(id);
      if (success) {
        fetchCustomers(searchQuery);
      } else {
        alert("Failed to delete customer");
      }
    }
  };

  const handleFormSuccess = () => {
    setIsModalOpen(false);
    fetchCustomers(searchQuery);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-heading font-bold text-foreground">Clientes</h1>
          <p className="text-muted-foreground">Gestionar base de datos de clientes.</p>
        </div>
        <Button onClick={handleCreateClick}>+ Nuevo Cliente</Button>
      </div>

      <div className="flex gap-2">
        <form onSubmit={handleSearch} className="flex-1 flex gap-2">
          <Input
            placeholder="Buscar clientes..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="max-w-md"
          />
          <Button type="submit" variant="secondary">Buscar</Button>
        </form>
      </div>

      <div className="bg-card border border-border rounded-xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-muted/50 text-muted-foreground uppercase text-xs">
              <tr>
                <th className="px-6 py-3">Nombre</th>
                <th className="px-6 py-3">Teléfono</th>
                <th className="px-6 py-3">Correo</th>
                <th className="px-6 py-3 text-right">Acciones</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {loading ? (
                <tr><td colSpan={4} className="p-4 text-center">Cargando...</td></tr>
              ) : customers.length === 0 ? (
                <tr><td colSpan={4} className="p-4 text-center">No se encontraron clientes.</td></tr>
              ) : (
                customers.map((c) => (
                  <tr key={c.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-3 font-medium">{c.firstName} {c.lastName}</td>
                    <td className="px-6 py-3">{c.phoneNumber}</td>
                    <td className="px-6 py-3">{c.email || "-"}</td>
                    <td className="px-6 py-3 text-right space-x-2">
                      <Button variant="outline" size="sm" onClick={() => handleEditClick(c)}>Editar</Button>
                      <Button variant="outline" size="sm" className="text-red-500 hover:text-red-600" onClick={() => c.id && handleDeleteClick(c.id)}>Eliminar</Button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingCustomer ? "Editar Cliente" : "Nuevo Cliente"}
      >
        <CustomerForm
          initialData={editingCustomer}
          onSuccess={handleFormSuccess}
          onCancel={() => setIsModalOpen(false)}
        />
      </Modal>
    </div>
  );
}
