// anotame-web/src/routes/(app)/dashboard/operations/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiService, API_SALES } from '$lib/services/api.svelte';
  import { Button } from '$lib/components/ui/button';
  import * as Table from '$lib/components/ui/table';
  import { translateStatus, getStatusColor } from '$lib/utils/statusUtils';
  import { formatDate } from '$lib/utils/formatUtils';
  import { adaptiveConfirm } from '$lib/components/ui/responsive/confirm-state.svelte';
  import { toast } from 'svelte-sonner';
  import { CheckCircle2, Eye } from 'lucide-svelte';

  let workOrders = $state<any[]>([]);
  let loading = $state(true);

  async function fetchWorkOrders() {
    loading = true;
    try {
      const allOrders = await apiService.request<any[]>(`${API_SALES}/orders`);
      workOrders = (allOrders || []).filter(o => o.status === 'IN_PROGRESS');
    } catch (e: any) {
      console.error(e);
      toast.error("Error al cargar las órdenes de trabajo");
      workOrders = [];
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchWorkOrders();
  });

  async function handleComplete(order: any) {
    const ok = await adaptiveConfirm({
      title: 'Marcar como Listo',
      description: `¿Desea marcar la orden ${order.ticketNumber} como lista? El estado cambiará a LISTO.`
    });
    if (!ok) return;

    try {
      await apiService.request(`${API_SALES}/orders/${order.id}/status`, {
        method: 'PATCH',
        body: JSON.stringify({ status: 'READY' })
      });
      toast.success("¡Orden marcada como lista!", { description: order.ticketNumber });
      fetchWorkOrders();
    } catch (e: any) {
      console.error(e);
      toast.error("Error al actualizar el estado", { description: e.message });
    }
  }
</script>

<div class="space-y-6 animate-in fade-in duration-300">
  <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
    <div>
      <h1 class="text-3xl font-heading font-bold text-foreground">Control de Operaciones</h1>
      <p class="text-muted-foreground">Órdenes en progreso pendientes de completar.</p>
    </div>
    <div class="text-sm text-muted-foreground bg-card border border-border px-4 py-2 rounded-lg">
      {workOrders.length} {workOrders.length === 1 ? 'orden' : 'órdenes'} en progreso
    </div>
  </div>

  <div class="bg-card border border-border rounded-xl overflow-x-auto shadow-sm">
    <Table.Root class="w-full min-w-[800px]">
      <Table.Header>
        <Table.Row>
          <Table.Head class="px-6 py-4">Ticket</Table.Head>
          <Table.Head class="px-6 py-4">Cliente</Table.Head>
          <Table.Head class="px-6 py-4">Estado</Table.Head>
          <Table.Head class="px-6 py-4">Servicios</Table.Head>
          <Table.Head class="px-6 py-4">Fecha Límite</Table.Head>
          <Table.Head class="px-6 py-4 text-right">Acciones</Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#if loading}
          <Table.Row>
            <Table.Cell colspan={6} class="h-24 text-center">
              Cargando...
            </Table.Cell>
          </Table.Row>
        {:else if workOrders.length === 0}
          <Table.Row>
            <Table.Cell colspan={6} class="h-24 text-center text-muted-foreground">
              No hay órdenes en progreso.
            </Table.Cell>
          </Table.Row>
        {:else}
          {#each workOrders as wo (wo.id)}
            <Table.Row class="hover:bg-muted/30 transition-colors">
              <Table.Cell class="px-6 py-4 font-medium font-mono text-sm">{wo.ticketNumber}</Table.Cell>
              <Table.Cell class="px-6 py-4">{wo.customer?.firstName} {wo.customer?.lastName}</Table.Cell>
              <Table.Cell class="px-6 py-4">
                <span class={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(wo.status)}`}>
                  {translateStatus(wo.status)}
                </span>
              </Table.Cell>
              <Table.Cell class="px-6 py-4 text-sm text-muted-foreground max-w-xs truncate">
                {wo.items?.map((i: any) => i.services?.map((s: any) => s.serviceName).join(', ')).filter(Boolean).join('; ') || '-'}
              </Table.Cell>
              <Table.Cell class="px-6 py-4 text-muted-foreground text-sm">
                {formatDate(wo.committedDeadline)}
              </Table.Cell>
              <Table.Cell class="px-6 py-4 text-right space-x-2">
                <Button
                  variant="outline"
                  size="sm"
                  class="h-10 px-4 touch-manipulation font-medium"
                  href={`/dashboard/orders/${wo.id}`}
                >
                  <Eye class="w-4 h-4 mr-2" />
                  Ver
                </Button>
                <Button
                  size="sm"
                  class="h-10 px-4 touch-manipulation font-medium bg-emerald-600 hover:bg-emerald-700 text-white"
                  onclick={() => handleComplete(wo)}
                >
                  <CheckCircle2 class="w-4 h-4 mr-2" />
                  Marcar Listo
                </Button>
              </Table.Cell>
            </Table.Row>
          {/each}
        {/if}
      </Table.Body>
    </Table.Root>
  </div>
</div>

// anotame-web-legacy/src/app/dashboard/operations/page.tsx
"use client";

import { useEffect, useState } from "react";
import { API_SALES } from "@/lib/api"; // Changed to API_SALES
import { OrderResponse } from "@/types/dtos"; // Changed type
import { translateStatus, getStatusColor } from "@/utils/statusUtils";
import { formatDate } from "@/utils/formatUtils";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/Table";
import { Button } from "@/components/ui/Button";

export default function WorkOrdersPage() {
  const [workOrders, setWorkOrders] = useState<OrderResponse[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchWorkOrders = async () => {
    try {
      const res = await fetch(`${API_SALES}/orders`);
      if (res.ok) {
        const allOrders: OrderResponse[] = await res.json();
        // Client-side filtering for IN_PROGRESS orders
        // In a real microservices architecture, operations-service would sync this,
        // or we would have a specific endpoint /orders/search?status=IN_PROGRESS
        const filtered = allOrders.filter(o => o.status === 'IN_PROGRESS');
        setWorkOrders(filtered);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchWorkOrders();
  }, []);

  // Mock delete/complete for visualization using the new PATCH endpoint
  const handleComplete = async (id: string) => {
    if (!confirm("¿Desea marcar esta orden como lista? (Cambiará el estado a LISTO)")) return;
    // For now, let's just complete it to remove it from this view
    try {
      await fetch(`${API_SALES}/orders/${id}/status`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "READY" })
      });
      fetchWorkOrders();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold font-heading">Control de Operaciones</h1>
      </div>

      <div className="bg-card border border-border rounded-xl overflow-hidden">
        <Table className="w-full text-sm text-left">
          <TableHeader className="bg-muted/50 text-muted-foreground uppercase text-xs">
            <TableRow>
              <TableHead className="px-6 py-3">Orden de Venta</TableHead>
              <TableHead className="px-6 py-3">Cliente</TableHead>
              <TableHead className="px-6 py-3">Estado</TableHead>
              <TableHead className="px-6 py-3">Prendas</TableHead>
              <TableHead className="px-6 py-3">Fecha Límite</TableHead>
              <TableHead className="px-6 py-3 text-right">Acciones</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="divide-y divide-border">
            {loading ? <TableRow><TableCell colSpan={6} className="p-4 text-center">Cargando...</TableCell></TableRow> :
              workOrders.map(wo => (
                <TableRow key={wo.id} className="hover:bg-muted/30">
                  <TableCell className="px-6 py-3 font-medium font-mono text-xs">{wo.ticketNumber}</TableCell>
                  <TableCell className="px-6 py-3 text-xs">{wo.customer.firstName} {wo.customer.lastName}</TableCell>
                  <TableCell className="px-6 py-3">
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(wo.status)}`}>
                      {translateStatus(wo.status)}
                    </span>
                  </TableCell>
                  <TableCell className="px-6 py-3 text-xs">
                    {wo.items.map(i => i.services?.map(s => s.serviceName).join(", ")).filter(Boolean).join("; ")}
                  </TableCell>
                  <TableCell className="px-6 py-3 text-muted-foreground text-xs">
                    {formatDate(wo.committedDeadline)}
                  </TableCell>
                  <TableCell className="px-6 py-3 text-right">
                    <Button variant="ghost" size="sm" onClick={() => handleComplete(wo.id)} className="text-success hover:underline font-medium">Marcar Listo</Button>
                  </TableCell>
                </TableRow>
              ))}
            {!loading && workOrders.length === 0 && <TableRow><TableCell colSpan={6} className="p-4 text-center">No hay órdenes en progreso.</TableCell></TableRow>}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
