// anotame-web/src/routes/(app)/dashboard/catalog/garments/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiService, API_CATALOG } from '$lib/services/api.svelte';
  import { adaptiveConfirm } from '$lib/components/ui/responsive/confirm-state.svelte';
  import { toast } from 'svelte-sonner';
  import { authService } from '$lib/services/auth.svelte';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import * as Table from '$lib/components/ui/table';
  import { Edit, Trash2 } from 'lucide-svelte';
  
  import GarmentDialog from '$lib/components/catalog/garment-dialog.svelte';

  const isAdmin = $derived(authService.user?.role === 'ADMIN');

  let garments = $state<any[]>([]);
  let loading = $state(true);
  let searchQuery = $state('');
  
  // Single dialog state
  let editingGarment = $state<any | null>(null);

  // Reactive filtering! No useEffect needed.
  let filteredGarments = $derived(
    garments.filter(g => g.name.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  async function fetchGarments() {
    loading = true;
    try {
      const response = await apiService.request<any[]>(`${API_CATALOG}/catalog/garments`);
      garments = response || [];
    } catch (e: any) {
      toast.error(e.message || "Error al cargar las prendas");
      garments = [];
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchGarments();
  });

  function handleCreateClick() {
    editingGarment = { id: null, name: '', description: '' };
  }

  function handleEditClick(garment: any) {
    editingGarment = garment;
  }

  async function handleDeleteClick(garment: any) {
    const ok = await adaptiveConfirm({ title: 'Eliminar Prenda', description: `¿Estás seguro de que deseas eliminar ${garment.name}?` });
    if (ok) {
      try {
        await apiService.request(`${API_CATALOG}/catalog/garments/${garment.id}`, { method: 'DELETE' });
        toast.success("Prenda eliminada exitosamente");
        fetchGarments();
      } catch (e: any) {
        toast.error(e.message || "Error al eliminar la prenda");
      }
    }
  }

  function handleFormSuccess() {
    editingGarment = null;
    fetchGarments();
  }
</script>

<div class="space-y-6">
  <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
    <div>
      <h1 class="text-3xl font-heading font-bold text-foreground">Prendas</h1>
      <p class="text-muted-foreground">Gestionar tipos de prendas (Camisas, Pantalones, etc).</p>
    </div>
    {#if isAdmin}
      <Button onclick={handleCreateClick} class="w-full sm:w-auto h-12 touch-manipulation">+ Agregar Prenda</Button>
    {/if}
  </div>

  <div class="flex gap-2">
    <Input
      placeholder="Buscar por nombre..."
      bind:value={searchQuery}
      class="max-w-md h-12"
    />
  </div>

  <div class="bg-card border border-border rounded-xl overflow-x-auto shadow-sm">
    <Table.Root class="w-full min-w-[600px]">
      <Table.Header>
        <Table.Row>
          <Table.Head class="px-6 py-4">Nombre</Table.Head>
          <Table.Head class="px-6 py-4">Descripción</Table.Head>
          {#if isAdmin}
            <Table.Head class="px-6 py-4 text-right">Acciones</Table.Head>
          {/if}
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {#if loading}
          <Table.Row>
            <Table.Cell colspan={isAdmin ? 3 : 2} class="h-24 text-center">
              Cargando...
            </Table.Cell>
          </Table.Row>
        {:else if filteredGarments.length === 0}
          <Table.Row>
            <Table.Cell colspan={isAdmin ? 3 : 2} class="h-24 text-center text-muted-foreground">
              No se encontraron prendas.
            </Table.Cell>
          </Table.Row>
        {:else}
          {#each filteredGarments as garment (garment.id)}
            <Table.Row>
              <Table.Cell class="px-6 py-4 font-medium">{garment.name}</Table.Cell>
              <Table.Cell class="px-6 py-4 text-muted-foreground">{garment.description || "-"}</Table.Cell>
              {#if isAdmin}
                <Table.Cell class="px-6 py-4 text-right space-x-2">
                  <Button
                    variant="outline"
                    size="sm"
                    class="h-10 px-4 touch-manipulation font-medium"
                    onclick={() => handleEditClick(garment)}
                  >
                    <Edit class="w-4 h-4 mr-2" />
                    Editar
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    class="h-10 px-4 text-destructive hover:text-destructive/90 touch-manipulation font-medium"
                    onclick={() => handleDeleteClick(garment)}
                  >
                    <Trash2 class="w-4 h-4 mr-2" />
                    Eliminar
                  </Button>
                </Table.Cell>
              {/if}
            </Table.Row>
          {/each}
        {/if}
      </Table.Body>
    </Table.Root>
  </div>

  <GarmentDialog item={editingGarment} onClose={() => editingGarment = null} onSuccess={handleFormSuccess} />
</div>

// anotame-web-legacy/src/app/dashboard/catalog/garments/page.tsx
"use client";

import { useEffect, useState } from "react";
import { getAllGarments, createGarment, updateGarment, deleteGarment } from "@/services/catalog/garments";
import { GarmentTypeResponse, GarmentTypeRequest } from "@/types/dtos";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { Input } from "@/components/ui/Input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/Table";

import { useAuth } from "@/context/AuthContext";

export default function GarmentsPage() {
  const { user } = useAuth();
  const isAdmin = user?.role === 'ADMIN';

  const [garments, setGarments] = useState<GarmentTypeResponse[]>([]);
  const [loading, setLoading] = useState(true);

  // Modal States
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [garmentToEdit, setGarmentToEdit] = useState<GarmentTypeResponse | null>(null);
  const [garmentToDelete, setGarmentToDelete] = useState<GarmentTypeResponse | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Form State
  const [formData, setFormData] = useState<GarmentTypeRequest>({ name: "", description: "" });

  const fetchGarments = async () => {
    try {
      const data = await getAllGarments();
      setGarments(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchGarments();
  }, []);

  const resetForm = () => {
    setFormData({ name: "", description: "" });
    setIsCreateModalOpen(false);
    setGarmentToEdit(null);
  };

  // --- Create Logic ---
  const handleCreateSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSubmitting(true);
    try {
      await createGarment(formData);
      fetchGarments();
      resetForm();
    } catch (e) {
      console.error(e);
      alert("Failed to create garment type");
    } finally {
      setIsSubmitting(false);
    }
  };

  // --- Edit Logic ---
  const handleEditClick = (garment: GarmentTypeResponse) => {
    setFormData({
      name: garment.name,
      description: garment.description
    });
    setGarmentToEdit(garment);
  };

  const handleEditSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!garmentToEdit) return;

    setIsSubmitting(true);
    try {
      await updateGarment(garmentToEdit.id, formData);
      fetchGarments();
      resetForm();
    } catch (e) {
      console.error(e);
      alert("Failed to update garment type");
    } finally {
      setIsSubmitting(false);
    }
  };

  // --- Delete Logic ---
  const handleDeleteClick = (garment: GarmentTypeResponse) => {
    setGarmentToDelete(garment);
  };

  const confirmDelete = async () => {
    if (!garmentToDelete) return;
    setIsSubmitting(true);
    try {
      await deleteGarment(garmentToDelete.id);
      setGarments(garments.filter(g => g.id !== garmentToDelete.id));
      setGarmentToDelete(null);
    } catch (e) {
      console.error(e);
      alert("Failed to delete garment type");
    } finally {
      setIsSubmitting(false);
    }
  };

  // Search Filter
  const [searchQuery, setSearchQuery] = useState("");

  const filteredGarments = garments.filter(g =>
    g.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-heading font-brand text-foreground">Prendas</h1>
          <p className="text-muted-foreground">Gestionar tipos de prendas (Camisas, Pantalones, etc).</p>
        </div>
        {isAdmin && (
          <Button onClick={() => setIsCreateModalOpen(true)}>+ Agregar Prenda</Button>
        )}
      </div>

      <div className="flex gap-4 mb-4">
        <div className="flex-1 max-w-sm">
          <Input
            placeholder="Buscar por nombre..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      </div>

      <div className="border border-border rounded-lg overflow-hidden">
        <Table className="w-full text-sm text-left">
          <TableHeader className="bg-secondary/20 text-muted-foreground font-medium uppercase text-xs">
            <TableRow>
              <TableHead className="px-4 py-3">Nombre</TableHead>
              <TableHead className="px-4 py-3">Descripción</TableHead>
              {isAdmin && <TableHead className="px-4 py-3 text-right">Acciones</TableHead>}
            </TableRow>
          </TableHeader>
          <TableBody className="divide-y divide-border">
            {loading ? (
              <TableRow><TableCell colSpan={isAdmin ? 4 : 3} className="p-4 text-center">Cargando...</TableCell></TableRow>
            ) : filteredGarments.length === 0 ? (
              <TableRow><TableCell colSpan={isAdmin ? 4 : 3} className="p-4 text-center text-muted-foreground">No se encontraron prendas.</TableCell></TableRow>
            ) : (
              filteredGarments.map((garment) => (
                <TableRow key={garment.id} className="hover:bg-secondary/10 transition-colors">
                  <TableCell className="px-4 py-3">{garment.name}</TableCell>
                  <TableCell className="px-4 py-3 text-muted-foreground">{garment.description}</TableCell>
                  {isAdmin && (
                    <TableCell className="px-4 py-3 text-right flex justify-end gap-2">
                      <Button variant="outline" size="sm" onClick={() => handleEditClick(garment)}>Editar</Button>
                      <Button variant="danger" size="sm" onClick={() => handleDeleteClick(garment)}>Eliminar</Button>
                    </TableCell>
                  )}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      {/* Create Modal */}
      <Modal
        isOpen={isCreateModalOpen}
        onClose={() => !isSubmitting && setIsCreateModalOpen(false)}
        title="Crear Nueva Prenda"
      >
        <form onSubmit={handleCreateSubmit} className="space-y-4">
          <Input label="Nombre" placeholder="Pantalón de Mezclilla" value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} required />
          <Input label="Descripción" placeholder="Todo tipo de pantalones..." value={formData.description} onChange={(e) => setFormData({ ...formData, description: e.target.value })} />
          <div className="flex justify-end pt-2">
            <Button disabled={isSubmitting}>{isSubmitting ? "Guardando..." : "Crear"}</Button>
          </div>
        </form>
      </Modal>

      {/* Edit Modal */}
      <Modal
        isOpen={!!garmentToEdit}
        onClose={() => !isSubmitting && setGarmentToEdit(null)}
        title="Editar Prenda"
      >
        <form onSubmit={handleEditSubmit} className="space-y-4">
          <Input
            label="Nombre"
            value={formData.name}
            onChange={e => setFormData({ ...formData, name: e.target.value })}
            required
          />

          <Input
            label="Descripción"
            value={formData.description}
            onChange={e => setFormData({ ...formData, description: e.target.value })}
          />
          <div className="flex justify-end pt-2">
            <Button disabled={isSubmitting}>{isSubmitting ? "Guardando..." : "Guardar"}</Button>
          </div>
        </form>
      </Modal>

      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={!!garmentToDelete}
        onClose={() => setGarmentToDelete(null)}
        title="Confirmar Eliminación"
        description="¿Estás seguro de que deseas eliminar este tipo de prenda?"
        footer={
          <>
            <Button variant="outline" onClick={() => setGarmentToDelete(null)}>Cancelar</Button>
            <Button variant="danger" onClick={confirmDelete} disabled={isSubmitting}>
              {isSubmitting ? "Eliminando..." : "Eliminar"}
            </Button>
          </>
        }
      >
        <div className="py-4">
          <p className="text-sm">
            Estás a punto de eliminar <strong>{garmentToDelete?.name}</strong>.
          </p>
        </div>
      </Modal>
    </div >
  );
}
