// anotame-web-legacy/src/components/layout/MenuModal.tsx
"use client";

import { useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
    X,
    LogOut
} from "lucide-react";
import { menuItems, adminOnlyItems } from "@/config/menu";
import { useAuth } from "@/context/AuthContext";
import { Button } from "@/components/ui/Button";

interface MenuModalProps {
    isOpen: boolean;
    onClose: () => void;
    onOpenProfile?: () => void;
}


export function MenuModal({ isOpen, onClose, onOpenProfile }: MenuModalProps) {
    const pathname = usePathname();
    const { user, logout } = useAuth();

    // Close formatting on escape key
    useEffect(() => {
        const handleEsc = (e: KeyboardEvent) => {
            if (e.key === "Escape") onClose();
        };
        window.addEventListener("keydown", handleEsc);
        return () => window.removeEventListener("keydown", handleEsc);
    }, [onClose]);

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm animate-in fade-in zoom-in-95 duration-200">
            <div className="relative w-full max-w-5xl bg-card border border-border shadow-2xl rounded-xl overflow-hidden flex flex-col max-h-[90vh]">
                {/* Header */}
                <div className="flex items-center justify-between p-6 border-b border-border">
                    <div>
                        <h2 className="text-2xl font-bold font-heading">Menú Principal</h2>
                        <p className="text-muted-foreground">Selecciona una opción para navegar</p>
                    </div>
                    <Button variant="ghost" size="icon" onClick={onClose} className="h-12 w-12 rounded-full">
                        <X className="h-8 w-8" />
                    </Button>
                </div>

                {/* Grid Content */}
                <div className="flex-1 overflow-y-auto p-6">
                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                        {menuItems.filter(item => {
                            // RBAC Logic
                            const isAdmin = user?.role === 'ADMIN';

                            // Explicit Logic
                            if (adminOnlyItems.includes(item.name)) return isAdmin;

                            return true;
                        }).map((item) => {
                            const isActive = pathname === item.href;
                            const Icon = item.icon;

                            return (
                                <Link
                                    key={item.href}
                                    href={item.href}
                                    onClick={onClose}
                                    className={`flex flex-col items-center justify-center gap-4 p-8 rounded-xl border-2 transition-all hover:scale-105 active:scale-95
                    ${isActive
                                            ? "border-primary bg-primary/5 text-primary shadow-sm"
                                            : "border-border bg-card hover:border-primary/50 hover:bg-secondary/50 text-muted-foreground hover:text-foreground"
                                        }`}
                                >
                                    <Icon className={`w-12 h-12 ${isActive ? "text-primary" : "text-muted-foreground"}`} />
                                    <span className="text-lg font-semibold text-center">{item.name}</span>
                                </Link>
                            );
                        })}
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-border bg-muted/20 flex justify-between items-center">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center text-primary font-bold text-lg">
                            {user?.username?.charAt(0).toUpperCase() || "U"}
                        </div>
                        <div>
                            <div className="font-semibold">{user?.username || "Usuario"}</div>
                            <Button
                                variant="ghost"
                                className="h-auto p-0 text-xs text-muted-foreground hover:text-primary underline"
                                onClick={onOpenProfile}
                            >
                                Editar Credenciales
                            </Button>
                        </div>
                    </div>

                    <Button
                        variant="destructive"
                        size="lg"
                        onClick={logout}
                        className="gap-2"
                    >
                        <LogOut className="w-5 h-5" />
                        <span>Cerrar Sesión</span>
                    </Button>
                </div>
            </div>
        </div>
    );
}

// anotame-web/src/lib/components/layout/menu-modal.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/state';
  import XIcon from 'lucide-svelte/icons/x';
  import LogOutIcon from 'lucide-svelte/icons/log-out';
  import { menuItems, adminOnlyItems } from '$lib/config/menu';
  import { authService } from '$lib/services/auth.svelte';
  import { Button } from '$lib/components/ui/button';
  import * as m from '$lib/paraglide/messages';

  let { isOpen = $bindable(false), onOpenProfile } = $props<{
    isOpen: boolean;
    onOpenProfile?: () => void;
  }>();

  const user = $derived(authService.user);

  function handleClose() {
    isOpen = false;
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape" && isOpen) {
      handleClose();
    }
  }

  onMount(() => {
    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  });
</script>

{#if isOpen}
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm animate-in fade-in zoom-in-95 duration-200">
    <div class="relative w-full max-w-5xl bg-card border shadow-2xl rounded-xl overflow-hidden flex flex-col max-h-[90vh]">

      <!-- Header -->
      <div class="flex items-center justify-between p-6 border-b">
        <div>
          <h2 class="text-2xl font-bold font-heading">{m["nav.menu.title"]()}</h2>
          <p class="text-muted-foreground">{m["nav.menu.subtitle"]()}</p>
        </div>
        <Button variant="ghost" size="icon" onclick={handleClose} class="h-12 w-12 rounded-full">
          <XIcon class="h-8 w-8" />
        </Button>
      </div>

      <!-- Grid Content -->
      <div class="flex-1 overflow-y-auto p-6">
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {#each menuItems as item}
            {@const isAdmin = user?.role === 'ADMIN'}
            {@const isAllowed = adminOnlyItems.includes(item.key) ? isAdmin : true}
            {#if isAllowed}
              {@const isActive = page.url.pathname === item.href}
              {@const SvelteIcon = item.icon}
              <a
                href={item.href}
                onclick={handleClose}
                class="flex flex-col items-center justify-center gap-4 p-8 rounded-xl border-2 transition-all hover:scale-105 active:scale-95
                  {isActive
                    ? 'border-primary bg-primary/5 text-primary shadow-sm'
                    : 'border-border bg-card hover:border-primary/50 hover:bg-secondary/50 text-muted-foreground hover:text-foreground'
                  }"
              >
                <SvelteIcon class="w-12 h-12 {isActive ? 'text-primary' : 'text-muted-foreground'}" />
                <span class="text-lg font-semibold text-center">{item.getName()}</span>
              </a>
            {/if}
          {/each}
        </div>
      </div>

      <!-- Footer -->
      <div class="p-6 border-t bg-muted/20 flex justify-between items-center">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center text-primary font-bold text-lg">
            {user?.username?.charAt(0).toUpperCase() || "U"}
          </div>
          <div>
            <div class="font-semibold">{user?.username || m["common.user"]()}</div>
            <Button
              variant="ghost"
              class="h-auto p-0 text-xs text-muted-foreground hover:text-primary underline"
              onclick={() => { handleClose(); onOpenProfile?.(); }}
            >
              {m["nav.menu.editCredentials"]()}
            </Button>
          </div>
        </div>

        <Button
          variant="destructive"
          size="lg"
          onclick={() => authService.logout()}
          class="gap-2"
        >
          <LogOutIcon class="w-5 h-5" />
          <span>{m["nav.menu.logout"]()}</span>
        </Button>
      </div>

    </div>
  </div>
{/if}
