// anotame-web/src/app/dashboard/catalog/services/page.tsx
"use client";

import { useEffect, useState } from "react";
import { API_CATALOG } from "@/lib/api";
import { ServiceResponse, ServiceRequest } from "@/types/dtos";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { Input } from "@/components/ui/Input";

export default function ServicesPage() {
  const [services, setServices] = useState<ServiceResponse[]>([]);
  const [loading, setLoading] = useState(true);
  
  // Modal States
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [serviceToEdit, setServiceToEdit] = useState<ServiceResponse | null>(null);
  const [serviceToDelete, setServiceToDelete] = useState<ServiceResponse | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Form State
  const [formData, setFormData] = useState<ServiceRequest>({ 
    code: "", name: "", description: "", defaultDurationMin: 60, basePrice: 0 
  });

  const fetchServices = async () => {
    try {
      const res = await fetch(`${API_CATALOG}/catalog/services`);
      if (res.ok) {
        setServices(await res.json());
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchServices();
  }, []);

  const resetForm = () => {
    setFormData({ code: "", name: "", description: "", defaultDurationMin: 60, basePrice: 0 });
    setIsCreateModalOpen(false);
    setServiceToEdit(null);
  };

  // --- Create Logic ---
  const handleCreateSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSubmitting(true);
    try {
        const res = await fetch(`${API_CATALOG}/catalog/services`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(formData),
        });
        if (res.ok) {
            fetchServices();
            resetForm();
        } else {
            alert("Failed to create service");
        }
    } catch (e) {
        console.error(e);
    } finally {
        setIsSubmitting(false);
    }
  };

  // --- Edit Logic ---
  const handleEditClick = (service: ServiceResponse) => {
    setFormData({
        code: service.code,
        name: service.name,
        description: service.description,
        defaultDurationMin: service.defaultDurationMin,
        basePrice: service.basePrice
    });
    setServiceToEdit(service);
  };

  const handleEditSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!serviceToEdit) return;

    setIsSubmitting(true);
    try {
        const res = await fetch(`${API_CATALOG}/catalog/services/${serviceToEdit.id}`, {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(formData),
        });
        if (res.ok) {
            fetchServices();
            resetForm();
        } else {
            alert("Failed to update service");
        }
    } catch (e) {
        console.error(e);
    } finally {
        setIsSubmitting(false);
    }
  };

  // --- Delete Logic ---
  const handleDeleteClick = (service: ServiceResponse) => {
    setServiceToDelete(service);
  };

  const confirmDelete = async () => {
    if (!serviceToDelete) return;
    setIsSubmitting(true);
    try {
        const res = await fetch(`${API_CATALOG}/catalog/services/${serviceToDelete.id}`, { method: "DELETE" });
        if (res.ok) {
            setServices(services.filter(s => s.id !== serviceToDelete.id));
            setServiceToDelete(null);
        } else {
            alert("Failed to delete service");
        }
    } catch (e) {
        console.error(e);
    } finally {
        setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
            <h1 className="text-3xl font-heading font-bold text-foreground">Services</h1>
            <p className="text-muted-foreground">Manage offered services and pricing.</p>
        </div>
        <Button onClick={() => { resetForm(); setIsCreateModalOpen(true); }}>
          + Add Service
        </Button>
      </div>

      <div className="bg-card border border-border rounded-xl  overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
            <thead className="bg-muted/50 text-muted-foreground uppercase text-xs">
                <tr>
                <th className="px-6 py-3">Code</th>
                <th className="px-6 py-3">Name</th>
                <th className="px-6 py-3">Duration (min)</th>
                <th className="px-6 py-3">Price</th>
                <th className="px-6 py-3 text-right">Actions</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-border">
                {loading ? <tr><td colSpan={5} className="p-4 text-center">Loading...</td></tr> : 
                services.map(s => (
                <tr key={s.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-3 font-medium">{s.code}</td>
                    <td className="px-6 py-3">{s.name}</td>
                    <td className="px-6 py-3">{s.defaultDurationMin}</td>
                    <td className="px-6 py-3">${s.basePrice}</td>
                    <td className="px-6 py-3 text-right">
                        <div className="flex justify-end gap-2">
                             <Button variant="outline" size="sm" onClick={() => handleEditClick(s)}>Edit</Button>
                             <Button variant="danger" size="sm" onClick={() => handleDeleteClick(s)}>Delete</Button>
                        </div>
                    </td>
                </tr>
                ))}
                {!loading && services.length === 0 && <tr><td colSpan={5} className="p-4 text-center">No services found.</td></tr>}
            </tbody>
            </table>
        </div>
      </div>

      {/* Create Modal */}
      <Modal
        isOpen={isCreateModalOpen}
        onClose={resetForm}
        title="Add New Service"
        description="Create a new service offering."
        footer={
            <>
                <Button variant="outline" onClick={resetForm}>Cancel</Button>
                <Button onClick={() => handleCreateSubmit()} disabled={isSubmitting}>
                    {isSubmitting ? "Saving..." : "Create Service"}
                </Button>
            </>
        }
      >
        <form className="space-y-4 py-2">
            <div className="grid grid-cols-2 gap-4">
                <Input 
                    label="Code" 
                    placeholder="e.g. HEM"
                    value={formData.code}
                    onChange={e => setFormData({...formData, code: e.target.value})}
                    required
                />
                <Input 
                    label="Name" 
                    placeholder="e.g. Hemming"
                    value={formData.name}
                    onChange={e => setFormData({...formData, name: e.target.value})}
                    required
                />
            </div>
            <div className="grid grid-cols-2 gap-4">
                <Input 
                    label="Duration (min)" 
                    type="number"
                    value={formData.defaultDurationMin}
                    onChange={e => setFormData({...formData, defaultDurationMin: parseInt(e.target.value) || 0})}
                />
                <Input 
                    label="Base Price" 
                    type="number"
                    step="0.01"
                    value={formData.basePrice}
                    onChange={e => setFormData({...formData, basePrice: parseFloat(e.target.value) || 0})}
                />
            </div>
            <Input 
                label="Description" 
                placeholder="Description of the service"
                value={formData.description}
                onChange={e => setFormData({...formData, description: e.target.value})}
            />
        </form>
      </Modal>

      {/* Edit Modal */}
      <Modal
        isOpen={!!serviceToEdit}
        onClose={resetForm}
        title="Edit Service"
        description="Update service details."
        footer={
            <>
                 <Button variant="outline" onClick={resetForm}>Cancel</Button>
                 <Button onClick={() => handleEditSubmit()} disabled={isSubmitting}>
                    {isSubmitting ? "Saving..." : "Save Changes"}
                 </Button>
            </>
        }
      >
         <form className="space-y-4 py-2">
            <div className="grid grid-cols-2 gap-4">
                <Input 
                    label="Code" 
                    value={formData.code}
                    onChange={e => setFormData({...formData, code: e.target.value})}
                    required
                />
                <Input 
                    label="Name" 
                    value={formData.name}
                    onChange={e => setFormData({...formData, name: e.target.value})}
                    required
                />
            </div>
            <div className="grid grid-cols-2 gap-4">
                <Input 
                    label="Duration (min)" 
                    type="number"
                    value={formData.defaultDurationMin}
                    onChange={e => setFormData({...formData, defaultDurationMin: parseInt(e.target.value) || 0})}
                />
                <Input 
                    label="Base Price" 
                    type="number"
                    step="0.01"
                    value={formData.basePrice}
                    onChange={e => setFormData({...formData, basePrice: parseFloat(e.target.value) || 0})}
                />
            </div>
            <Input 
                label="Description" 
                value={formData.description}
                onChange={e => setFormData({...formData, description: e.target.value})}
            />
        </form>
      </Modal>

      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={!!serviceToDelete}
        onClose={() => setServiceToDelete(null)}
        title="Confirm Deletion"
        description="Are you sure you want to delete this service?"
        footer={
            <>
                <Button variant="outline" onClick={() => setServiceToDelete(null)}>Cancel</Button>
                <Button variant="danger" onClick={confirmDelete} disabled={isSubmitting}>
                    {isSubmitting ? "Deleting..." : "Delete"}
                </Button>
            </>
        }
      >
         <div className="py-4">
            <p className="text-sm">
                You are about to delete <strong>{serviceToDelete?.name}</strong>.
            </p>
        </div>
      </Modal>
    </div>
  );
}

// anotame-web/src/routes/(app)/dashboard/catalog/services/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as m from '$lib/paraglide/messages';
  import { apiService, API_CATALOG } from '$lib/services/api.svelte';
  import { authService } from '$lib/services/auth.svelte';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Edit, Trash2 } from '@lucide/svelte';
  import { adaptiveConfirm } from '$lib/components/ui/responsive/confirm-state.svelte';
  import { AdaptiveSelect } from '$lib/components/ui/responsive';
  import { toast } from 'svelte-sonner';
  import DataTableWrapper from '$lib/components/ui/DataTableWrapper.svelte';
  import CardGridWrapper from '$lib/components/ui/CardGridWrapper.svelte';
  import { useIsMobile } from '$lib/hooks/use-mobile.svelte';
  import type { ColumnDef, Row } from '@tanstack/table-core';
  import type { GarmentTypeResponse, ServiceResponse } from '$lib/types/dtos';

  const mobile = useIsMobile();

  import ServiceDialog from '$lib/components/catalog/service-dialog.svelte';

  const isAdmin = $derived(authService.user?.role === 'ADMIN');

  type ServiceEditorItem = Omit<Partial<ServiceResponse>, 'id'> & { id?: string | null };

  let services = $state<ServiceResponse[]>([]);
  let garments = $state<GarmentTypeResponse[]>([]);
  let loading = $state(true);

  // Filters
  let searchQuery = $state('');
  let garmentFilter = $state('');

  // Single dialog state
  let editingService = $state<ServiceEditorItem | null>(null);

  // Reactive filtering
  let filteredServices = $derived.by(() => {
    return services.filter(s => {
      const matchesSearch = s.name.toLowerCase().includes(searchQuery.toLowerCase());
      if (!matchesSearch) return false;

      if (garmentFilter) {
        if (s.garmentTypeId !== garmentFilter) return false;
      }

      return true;
    });
  });

  let columns = $derived<ColumnDef<ServiceResponse>[]>([
    { accessorKey: 'name', header: m["catalog.services.colName"](), enableSorting: true, meta: { cardGroup: 'header' } },
    { id: 'garment', accessorFn: (row) => getGarmentName(row.garmentTypeId), header: m["catalog.services.colGarment"](), enableSorting: true, meta: { cardGroup: 'header' } },
    { accessorKey: 'defaultDurationMin', header: m["catalog.services.colDuration"](), enableSorting: true, meta: { cardGroup: 'body' } },
    { id: 'price', accessorFn: (row) => `$${row.basePrice.toFixed(2)}`, header: m["catalog.services.colPrice"](), enableSorting: true, meta: { cardGroup: 'header' } },
    ...(isAdmin ? [{ id: 'actions', header: m["common.actions"](), enableSorting: false, meta: { cardGroup: 'hidden' } } as ColumnDef<ServiceResponse>] : []),
  ]);

  async function fetchData() {
    loading = true;
    try {
      const [servicesData, garmentsData] = await Promise.all([
        apiService.request<ServiceResponse[]>(`${API_CATALOG}/catalog/services`),
        apiService.request<GarmentTypeResponse[]>(`${API_CATALOG}/catalog/garments`)
      ]);
      services = servicesData || [];
      garments = garmentsData || [];
    } catch (e: any) {
      toast.error(e.message || m["catalog.services.loadError"]());
      services = [];
      garments = [];
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchData();
  });

  function handleCreateClick() {
    editingService = {
      id: null,
      name: '',
      description: '',
      basePrice: 0,
      defaultDurationMin: 30,
      garmentTypeId: ''
    };
  }

  function handleEditClick(service: ServiceResponse) {
    editingService = service;
  }

  async function handleDeleteClick(service: ServiceResponse) {
    const ok = await adaptiveConfirm({
      title: m["catalog.services.deleteTitle"](),
      description: m["catalog.services.deleteDescription"]({ name: service.name })
    });
    if (ok) {
      try {
        await apiService.request(`${API_CATALOG}/catalog/services/${service.id}`, { method: 'DELETE' });
        toast.success(m["catalog.services.deleteSuccess"]());
        fetchData();
      } catch (e: any) {
        toast.error(e.message || m["catalog.services.deleteError"]());
      }
    }
  }

  function handleFormSuccess() {
    editingService = null;
    fetchData();
  }

  function getGarmentName(garmentTypeId?: string): string {
    const g = garments.find(g => g.id === garmentTypeId);
    return g?.name || '-';
  }
</script>

<div class="space-y-6 animate-in fade-in duration-300">
  <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
    <div>
      <h1 class="text-3xl font-heading font-bold text-foreground">{m["catalog.services.title"]()}</h1>
      <p class="text-muted-foreground">{m["catalog.services.description"]()}</p>
    </div>
    {#if isAdmin}
      <Button onclick={handleCreateClick} class="w-full sm:w-auto h-12 px-6 text-lg font-bold touch-manipulation shadow-md">
        {m["catalog.services.addButton"]()}
      </Button>
    {/if}
  </div>

  <!-- External Filters -->
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4 p-5 bg-card border border-border rounded-xl shadow-sm">
    <div class="col-span-1 md:col-span-2 space-y-1.5">
      <label class="text-xs font-bold uppercase tracking-wider text-muted-foreground" for="search-services">{m["catalog.services.searchLabel"]()}</label>
      <Input
        id="search-services"
        placeholder={m["catalog.services.searchPlaceholder"]()}
        bind:value={searchQuery}
        class="h-12 text-base touch-manipulation"
      />
    </div>
    <div class="space-y-1.5">
      <label class="text-xs font-bold uppercase tracking-wider text-muted-foreground" for="filter-garment-service">{m["catalog.services.filterGarmentLabel"]()}</label>
      <AdaptiveSelect
        id="filter-garment-service"
        bind:value={garmentFilter}
        placeholder={m["catalog.services.filterGarmentPlaceholder"]()}
        items={garments.map(g => ({ value: g.id, label: g.name }))}
        allowClear={true}
        clearText={m["catalog.services.filterGarmentClear"]()}
      />
    </div>
  </div>

  <!-- Table / Cards -->
  <div class="bg-card border border-border rounded-xl overflow-hidden shadow-sm p-4">
    {#snippet serviceActions(row: Row<ServiceResponse>)}
      <div class="flex justify-end gap-2">
        <Button
          variant="outline"
          size="sm"
          class="h-10 px-4 touch-manipulation font-medium"
          onclick={() => handleEditClick(row.original)}
        >
          <Edit class="w-4 h-4 mr-2" />
          {m["common.edit"]()}
        </Button>
        <Button
          variant="outline"
          size="sm"
          class="h-10 px-4 text-destructive hover:text-destructive/90 touch-manipulation font-medium"
          onclick={() => handleDeleteClick(row.original)}
        >
          <Trash2 class="w-4 h-4 mr-2" />
          {m["common.delete"]()}
        </Button>
      </div>
    {/snippet}

    {#if mobile.current}
      <CardGridWrapper
        {columns}
        data={filteredServices}
        {loading}
        showFilter={false}
        emptyMessage={m["catalog.services.emptyMessage"]()}
        actionCell={serviceActions}
      />
    {:else}
      <DataTableWrapper
        {columns}
        data={filteredServices}
        {loading}
        showFilter={false}
        emptyMessage={m["catalog.services.emptyMessage"]()}
        filterPlaceholder={m["catalog.services.filterPlaceholder"]()}
        actionCell={serviceActions}
      />
    {/if}
  </div>

  <ServiceDialog
    item={editingService}
    {garments}
    onClose={() => editingService = null}
    onSuccess={handleFormSuccess}
  />
</div>
