// anotame-web/src/components/orders/wizard/ItemsStep.tsx
"use client";

import { useMemo, useState } from "react";
import { DraftOrder } from "@/services/local/DraftsService";
import { ItemSubWizard } from "./ItemSubWizard";
import { Button } from "@/components/ui/Button";
import { Plus, Trash2, Edit } from "lucide-react";

interface StepProps {
    draft: DraftOrder;
    updateDraft: (updates: Partial<DraftOrder>) => void;
    onNext: () => void;
    onBack: () => void;
}

export function ItemsStep({ draft, updateDraft, onNext, onBack }: StepProps) {
    const [isAddingItem, setIsAddingItem] = useState(false);
    const [editingIndex, setEditingIndex] = useState<number | null>(null);

    const handleSaveItem = (item: any) => {
        const newItems = [...(draft.items || [])];
        if (editingIndex !== null) {
            newItems[editingIndex] = item;
        } else {
            newItems.push(item);
        }
        updateDraft({ items: newItems });
        setIsAddingItem(false);
        setEditingIndex(null);
    };

    const handleEditItem = (index: number) => {
        setEditingIndex(index);
        setIsAddingItem(true);
    };

    const handleDeleteItem = (index: number) => {
        const newItems = [...(draft.items || [])];
        newItems.splice(index, 1);
        updateDraft({ items: newItems });
    };

    const total = useMemo(() => {
        return (draft.items || []).reduce((acc, item) => {
            const servicesTotal = (item.services || []).reduce((sAcc, s) => sAcc + s.unitPrice + (s.adjustmentAmount || 0), 0);
            return acc + servicesTotal;
        }, 0);
    }, [draft.items]);

    if (isAddingItem) {
        return (
            <ItemSubWizard
                initialItem={editingIndex !== null ? draft.items![editingIndex] : undefined}
                onSave={handleSaveItem}
                onCancel={() => {
                    setIsAddingItem(false);
                    setEditingIndex(null);
                }}
            />
        );
    }

    return (
        <div className="flex flex-col h-full gap-6">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-xl font-semibold">Paso 2: Prendas y Servicios</h2>
                    <p className="text-muted-foreground">Agrega las prendas que el cliente deja.</p>
                </div>
                <Button onClick={() => setIsAddingItem(true)} size="lg" className="rounded-full h-12 px-6">
                    <Plus className="w-5 h-5 mr-2" />
                    Agregar Prenda
                </Button>
            </div>

            <div className="flex-1 overflow-y-auto space-y-4 pr-2">
                {(!draft.items || draft.items.length === 0) ? (
                    <div className="h-40 flex flex-col items-center justify-center border-2 border-dashed border-muted rounded-xl text-muted-foreground">
                        <p>No hay prendas agregadas.</p>
                        <div
                            className="mt-4 text-primary font-medium cursor-pointer hover:underline"
                            onClick={() => setIsAddingItem(true)}
                        >
                            + Agregar la primera prenda
                        </div>
                    </div>
                ) : (
                    draft.items.map((item, idx) => (
                        <div key={idx} className="bg-card border border-border p-4 rounded-xl flex items-center justify-between shadow-sm animate-in fade-in slide-in-from-bottom-2">
                            <div className="flex-1">
                                <div className="font-bold text-lg">{item.garmentName}</div>
                                <div className="text-sm text-muted-foreground">
                                    {item.services?.map((s, i) => (
                                        <div key={i} className="flex gap-2">
                                            <span>• {s.serviceName}</span>
                                            <span className="font-mono text-xs">
                                                ${(s.unitPrice + (s.adjustmentAmount || 0)).toFixed(2)}
                                                {s.adjustmentAmount ? ` (Adj: ${s.adjustmentAmount})` : ''}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                                {item.notes && (
                                    <div className="text-xs text-muted-foreground mt-1 bg-secondary/50 p-1 rounded inline-block">
                                        Nota: {item.notes}
                                    </div>
                                )}
                            </div>
                            <div className="text-right px-4">
                                <div className="font-mono font-bold text-lg">
                                    ${(item.services || []).reduce((acc, s) => acc + s.unitPrice + (s.adjustmentAmount || 0), 0).toFixed(2)}
                                </div>
                            </div>
                            <div className="flex gap-2">
                                <Button variant="ghost" size="icon" onClick={() => handleEditItem(idx)}>
                                    <Edit className="w-5 h-5 text-muted-foreground hover:text-primary" />
                                </Button>
                                <Button variant="ghost" size="icon" onClick={() => handleDeleteItem(idx)}>
                                    <Trash2 className="w-5 h-5 text-muted-foreground hover:text-destructive" />
                                </Button>
                            </div>
                        </div>
                    ))
                )}
            </div>

            <div className="border-t border-border pt-4 mt-auto">
                <div className="flex justify-between items-center mb-4 px-2">
                    <span className="text-lg font-medium">Total Estimado:</span>
                    <span className="text-2xl font-bold">${total.toFixed(2)}</span>
                </div>
                <div className="flex justify-between gap-4">
                    <Button variant="outline" size="lg" onClick={onBack} className="flex-1">Atrás</Button>
                    <Button size="lg" onClick={onNext} disabled={!draft.items || draft.items.length === 0} className="flex-1">
                        Continuar al Pago
                    </Button>
                </div>
            </div>
        </div>
    );
}

// anotame-web/src/lib/components/orders/wizard/items-step.svelte
<script lang="ts">
   import { orderWizardState } from '$lib/services/orders/OrderWizardState.svelte';
   import ItemSubWizard from './item-sub-wizard.svelte';
   import { Button } from '$lib/components/ui/button';
   import { Plus, Trash2, Edit, Copy } from 'lucide-svelte';
   import { toast } from 'svelte-sonner';

   let { onNext, onBack } = $props<{ onNext: () => void, onBack: () => void }>();

   let isAddingItem = $state(false);
   let editingIndex = $state<number | null>(null);

   let draft = $derived(orderWizardState.activeDraft || {} as any);
   let items = $derived(draft?.items || []);

   let total = $derived(items.reduce((acc, item) => {
       const servicesTotal = (item.services || []).reduce((sAcc, s) => sAcc + s.unitPrice + (s.adjustmentAmount || 0), 0);
       return acc + servicesTotal;
   }, 0));

   function handleSaveItem(item: any) {
       let newItems = [...items];
       if (editingIndex !== null) {
           newItems[editingIndex] = item;
           toast.success("Prenda actualizada", { description: item.garmentName });
       } else {
           newItems.push(item);
           toast.success("Prenda agregada", { description: item.garmentName });
       }
       orderWizardState.updateActiveDraft({ items: newItems });
       isAddingItem = false;
       editingIndex = null;
   }

   function handleEditItem(index: number) {
       editingIndex = index;
       isAddingItem = true;
   }

   function handleDeleteItem(index: number) {
       let newItems = [...items];
       const deletedGarment = newItems[index].garmentName;
       newItems.splice(index, 1);
       orderWizardState.updateActiveDraft({ items: newItems });
       toast.info("Prenda eliminada", { description: deletedGarment });
   }

   function handleDuplicateItem(index: number) {
       const itemToDuplicate = items[index];
       const newItem = {
           ...itemToDuplicate,
           notes: itemToDuplicate.notes ? `${itemToDuplicate.notes} (Copia)` : '(Copia)',
           services: itemToDuplicate.services?.map(s => ({ ...s }))
       };
       let newItems = [...items];
       newItems.splice(index + 1, 0, newItem);
       orderWizardState.updateActiveDraft({ items: newItems });
       toast.success("Prenda duplicada", { description: `${itemToDuplicate.garmentName}` });
   }
</script>

{#if isAddingItem}
   <ItemSubWizard
       initialItem={editingIndex !== null ? items[editingIndex] : undefined}
       onSave={handleSaveItem}
       onCancel={() => {
           isAddingItem = false;
           editingIndex = null;
       }}
   />
{:else}
   <div class="flex flex-col h-full gap-6">
       <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
           <div>
               <h2 class="text-xl font-semibold">Paso 2: Prendas y Servicios</h2>
               <p class="text-muted-foreground">Agrega las prendas que el cliente deja.</p>
           </div>
           <Button onclick={() => isAddingItem = true} size="lg" class="rounded-xl h-14 px-8 w-full sm:w-auto touch-manipulation shadow-md">
               <Plus class="w-5 h-5 mr-2" />
               Agregar Prenda
           </Button>
       </div>

       <div class="flex-1 overflow-y-auto space-y-4 pr-2 custom-scrollbar">
           {#if items.length === 0}
               <div class="h-64 flex flex-col items-center justify-center border-2 border-dashed border-muted rounded-2xl text-muted-foreground w-full">
                   <p class="text-lg">No hay prendas agregadas.</p>
                   <button
                       class="mt-6 text-primary font-bold text-lg cursor-pointer hover:underline touch-manipulation py-4 px-6 bg-primary/5 rounded-xl transition-colors"
                       onclick={() => isAddingItem = true}
                   >
                       + Agregar la primera prenda
                   </button>
               </div>
           {:else}
               {#each items as item, idx}
                   <div class="bg-card border border-border p-5 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-sm animate-in fade-in slide-in-from-bottom-2">
                       <div class="flex-1">
                           <div class="font-bold text-xl mb-1">{item.garmentName}</div>
                           <div class="text-base text-muted-foreground space-y-1">
                               {#each (item.services || []) as s}
                                   <div class="flex gap-2 items-baseline">
                                       <span>• {s.serviceName}</span>
                                       <span class="font-mono text-sm bg-secondary px-1.5 py-0.5 rounded">
                                           ${(s.unitPrice + (s.adjustmentAmount || 0)).toFixed(2)}
                                           {s.adjustmentAmount ? ` (Adj: ${s.adjustmentAmount})` : ''}
                                       </span>
                                   </div>
                               {/each}
                           </div>
                           {#if item.notes}
                               <div class="text-sm text-muted-foreground mt-3 bg-secondary/50 p-2 rounded-lg border border-border/50 inline-block">
                                   <span class="font-semibold text-foreground mr-1">Nota:</span>{item.notes}
                               </div>
                           {/if}
                       </div>
                       
                       <div class="flex flex-row sm:flex-col items-center sm:items-end justify-between sm:justify-center w-full sm:w-auto mt-4 sm:mt-0 pt-4 sm:pt-0 border-t sm:border-t-0 border-border">
                           <div class="font-mono font-bold text-2xl text-primary sm:mb-4">
                               ${(item.services || []).reduce((acc: number, s: any) => acc + s.unitPrice + (s.adjustmentAmount || 0), 0).toFixed(2)}
                           </div>
                           <div class="flex gap-2 bg-secondary/30 p-1.5 rounded-xl">
                               <Button variant="ghost" size="icon" class="h-10 w-10 sm:h-12 sm:w-12 text-muted-foreground hover:bg-background hover:text-primary rounded-lg touch-manipulation shadow-sm border border-transparent hover:border-border" title="Duplicar" onclick={() => handleDuplicateItem(idx)}>
                                   <Copy class="w-5 h-5 sm:w-6 sm:h-6" />
                               </Button>
                               <Button variant="ghost" size="icon" class="h-10 w-10 sm:h-12 sm:w-12 text-muted-foreground hover:bg-background hover:text-primary rounded-lg touch-manipulation shadow-sm border border-transparent hover:border-border" title="Editar" onclick={() => handleEditItem(idx)}>
                                   <Edit class="w-5 h-5 sm:w-6 sm:h-6" />
                               </Button>
                               <Button variant="ghost" size="icon" class="h-10 w-10 sm:h-12 sm:w-12 text-muted-foreground hover:bg-background hover:text-destructive rounded-lg touch-manipulation shadow-sm border border-transparent hover:border-destructive/20" title="Eliminar" onclick={() => handleDeleteItem(idx)}>
                                   <Trash2 class="w-5 h-5 sm:w-6 sm:h-6" />
                               </Button>
                           </div>
                       </div>
                   </div>
               {/each}
           {/if}
       </div>

       <div class="border-t border-border pt-6 mt-auto">
           <div class="flex justify-between items-center mb-6 px-2">
               <span class="text-xl font-medium">Total Estimado:</span>
               <span class="text-4xl font-bold font-mono text-primary">${total.toFixed(2)}</span>
           </div>
           <div class="flex flex-col-reverse sm:flex-row gap-4">
               <Button variant="outline" class="w-full sm:w-auto sm:flex-1 h-16 text-lg rounded-xl touch-manipulation" onclick={onBack}>Atrás</Button>
               <Button class="w-full sm:w-auto sm:flex-1 h-16 text-lg rounded-xl shadow-lg touch-manipulation" onclick={onNext} disabled={items.length === 0}>
                   Continuar al Pago
               </Button>
           </div>
       </div>
   </div>
{/if}
