// anotame-web/src/routes/(app)/dashboard/orders/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiService, API_SALES, API_CATALOG } from '$lib/services/api.svelte';
  import { orderWizardState } from '$lib/services/orders/OrderWizardState.svelte';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { translateStatus } from '$lib/utils/statusUtils';
  import { formatCurrency, formatDate } from '$lib/utils/formatUtils';
  import { Edit, Trash2, Eye } from 'lucide-svelte';
  import { adaptiveConfirm } from '$lib/components/ui/responsive/confirm-state.svelte';
  import { AdaptiveSelect } from '$lib/components/ui/responsive';
  import { AdaptiveDatePicker } from '$lib/components/ui/responsive';
  import DataTableWrapper from '$lib/components/ui/DataTableWrapper.svelte';
  import type { ColumnDef } from '@tanstack/table-core';

  let view = $state<'active' | 'drafts'>('active');
  let orders = $state<any[]>([]);
  let garments = $state<any[]>([]);
  let loading = $state(true);

  // Filters
  let searchQuery = $state("");
  let garmentFilter = $state("");
  let dateFilter = $state("");

  let drafts = $derived(orderWizardState.drafts.current);

  const activeColumns: ColumnDef<any>[] = [
    { accessorKey: 'ticketNumber', header: 'Ticket', enableSorting: true },
    { id: 'customer', accessorFn: (row) => `${row.customer?.firstName ?? ''} ${row.customer?.lastName ?? ''}`, header: 'Cliente', enableSorting: true },
    { id: 'garments', accessorFn: (row) => row.items?.map((i: any) => i.garmentName).join(', '), header: 'Prendas (Resumen)', enableSorting: false },
    { id: 'status', accessorFn: (row) => translateStatus(row.status), header: 'Estado', enableSorting: true },
    { id: 'deadline', accessorFn: (row) => formatDate(row.committedDeadline), header: 'Entrega', enableSorting: true },
    { id: 'total', accessorFn: (row) => formatCurrency(row.totalAmount), header: 'Total', enableSorting: true },
    { id: 'actions', header: 'Acciones', enableSorting: false },
  ];

  const draftsColumns: ColumnDef<any>[] = [
    { id: 'draftId', accessorFn: (row) => row.id, header: 'ID (Temporal)', enableSorting: false },
    { id: 'customer', accessorFn: (row) => row.customer?.firstName ? `${row.customer.firstName} ${row.customer.lastName ?? ''}` : 'Sin nombre', header: 'Cliente', enableSorting: true },
    { id: 'garments', accessorFn: (row) => `${row.items?.length || 0} prendas`, header: 'Prendas', enableSorting: false },
    { id: 'lastModified', accessorFn: (row) => new Date(row.lastModified).toLocaleString(), header: 'Última Modificación', enableSorting: true },
    { id: 'actions', header: 'Acciones', enableSorting: false },
  ];

  async function fetchData() {
    loading = true;
    try {
      const [ordersData, garmentsData] = await Promise.all([
        apiService.request<any[]>(`${API_SALES}/orders`),
        apiService.request<any[]>(`${API_CATALOG}/catalog/garments`)
      ]);
      orders = ordersData || [];
      garments = garmentsData || [];
    } catch (e) {
      console.error(e);
      // Optional: Add toast error handling here
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchData();
  });

  async function handleDeleteDraft(id: string) {
    const ok = await adaptiveConfirm({
      title: 'Eliminar Borrador',
      description: '¿Estás seguro de eliminar este borrador? Esta acción no se puede deshacer.'
    });
    if (ok) {
      orderWizardState.deleteDraft(id);
    }
  }

  function setView(target: 'active' | 'drafts') {
    view = target;
  }

  // Derived filter logic
  let filteredOrders = $derived.by(() => {
    return orders.filter(order => {
      const query = searchQuery.toLowerCase();
      const matchesSearch =
        order.ticketNumber?.toLowerCase().includes(query) ||
        order.customer?.firstName?.toLowerCase().includes(query) ||
        order.customer?.lastName?.toLowerCase().includes(query);

      if (!matchesSearch) return false;

      if (garmentFilter) {
        const selectedGarment = garments.find(g => g.id === garmentFilter);
        if (selectedGarment) {
          const hasGarment = order.items?.some((item: any) =>
            item.garmentName === selectedGarment.name
          );
          if (!hasGarment) return false;
        }
      }

      if (dateFilter) {
        if (!order.committedDeadline) return false;
        const orderDate = order.committedDeadline.split('T')[0];
        if (orderDate !== dateFilter) return false;
      }

      return true;
    });
  });
</script>

<div class="space-y-6 animate-in fade-in duration-300">
  <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
    <div>
      <h1 class="text-3xl font-heading font-brand font-bold text-foreground">Pedidos</h1>
      <p class="text-muted-foreground">Ver y gestionar pedidos de clientes.</p>
    </div>
    <Button href="/dashboard/orders/new" class="w-full sm:w-auto h-12 px-6 text-lg font-bold touch-manipulation shadow-md">+ Nuevo Pedido</Button>
  </div>

  <div class="flex bg-muted/20 p-1.5 rounded-xl w-fit shadow-sm border border-border/50">
    <button
      onclick={() => setView('active')}
      class={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all disabled:opacity-50 touch-manipulation ${view === 'active'
        ? 'bg-background text-foreground shadow-sm border-border border'
        : 'text-muted-foreground hover:text-foreground hover:bg-muted/50 border border-transparent'
        }`}
    >
      Órdenes Activas
    </button>
    <button
      onclick={() => setView('drafts')}
      class={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all disabled:opacity-50 touch-manipulation ${view === 'drafts'
        ? 'bg-background text-foreground shadow-sm border-border border'
        : 'text-muted-foreground hover:text-foreground hover:bg-muted/50 border border-transparent'
        }`}
    >
      Borradores {drafts.length > 0 ? `(${drafts.length})` : ''}
    </button>
  </div>

  {#if view === 'active'}
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4 p-5 bg-card border border-border rounded-xl shadow-sm">
      <div class="col-span-1 md:col-span-2 space-y-1.5">
        <label class="text-xs font-bold uppercase tracking-wider text-muted-foreground" for="search-orders">Buscar</label>
        <Input
          id="search-orders"
          placeholder="Ticket, Nombre del Cliente..."
          bind:value={searchQuery}
          class="h-12 text-base touch-manipulation"
        />
      </div>
      <div class="space-y-1.5">
        <label class="text-xs font-bold uppercase tracking-wider text-muted-foreground" for="filter-garment">Filtrar por Prenda</label>
        <AdaptiveSelect
          id="filter-garment"
          bind:value={garmentFilter}
          placeholder="Selecciona una prenda"
          items={garments.map(g => ({ value: g.id, label: g.name }))}
          allowClear={true}
          clearText="Todas las prendas"
          class=""
        />
      </div>
      <div class="space-y-1.5">
        <label class="text-xs font-bold uppercase tracking-wider text-muted-foreground" for="filter-date">Fecha de Entrega</label>
        <AdaptiveDatePicker
          id="filter-date"
          bind:value={dateFilter}
          placeholder="Seleccionar fecha..."
        />
      </div>
    </div>

    <!-- Active Orders Table -->
    <div class="bg-card border border-border rounded-xl overflow-hidden shadow-sm p-4">
      <DataTableWrapper
        columns={activeColumns}
        data={filteredOrders}
        loading={loading}
        emptyMessage="No se encontraron pedidos."
        filterPlaceholder="Buscar pedidos..."
        showFilter={false}
      >
        {#snippet actionCell(row)}
          <div class="flex justify-end gap-2">
            <Button variant="ghost" href={`/dashboard/orders/${row.original.id}/edit`} class="h-10 px-4 font-medium hover:text-primary hover:bg-primary/10 touch-manipulation">
              <Edit class="w-4 h-4 mr-2" />
              Editar
            </Button>
            <Button variant="outline" href={`/dashboard/orders/${row.original.id}`} class="h-10 px-4 font-medium touch-manipulation">
              <Eye class="w-4 h-4 mr-2" />
              Detalles
            </Button>
          </div>
        {/snippet}
      </DataTableWrapper>
    </div>
  {:else}
    <!-- Drafts View -->
    <div class="bg-card border border-border rounded-xl overflow-hidden shadow-sm p-4">
      <DataTableWrapper
        columns={draftsColumns}
        data={drafts}
        emptyMessage="No hay borradores guardados."
        filterPlaceholder="Buscar borradores..."
        showFilter={false}
      >
        {#snippet actionCell(row)}
          <div class="flex justify-end gap-2">
            <Button variant="ghost" href={`/dashboard/orders/new?draftId=${row.original.id}`} class="h-10 px-4 font-medium hover:text-primary hover:bg-primary/10 touch-manipulation flex items-center justify-center">
              <Edit class="w-4 h-4 mr-2" />
              <span>Editar Borrador</span>
            </Button>
            <Button variant="ghost" class="h-10 px-4 font-medium text-destructive hover:text-destructive hover:bg-destructive/10 touch-manipulation" onclick={() => handleDeleteDraft(row.original.id)}>
              <Trash2 class="w-4 h-4 mr-2" />
              <span>Eliminar</span>
            </Button>
          </div>
        {/snippet}
      </DataTableWrapper>
    </div>
  {/if}
</div>

// anotame-web-legacy/src/app/dashboard/orders/page.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { getAllOrders } from "@/services/sales/orders";
import { getAllGarments } from "@/services/catalog/garments";
import { OrderResponse, GarmentTypeResponse } from "@/types/dtos";
import { DraftsService, DraftOrder } from "@/services/local/DraftsService";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { DatePicker } from "@/components/ui/DatePicker";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/Table";
import { translateStatus, getStatusColor } from "@/utils/statusUtils";
import { formatCurrency, formatDate } from "@/utils/formatUtils";
import { Edit, Trash2 } from "lucide-react";

export default function ServicesPage() {
  const [view, setView] = useState<'active' | 'drafts'>('active');
  const [orders, setOrders] = useState<OrderResponse[]>([]);
  const [drafts, setDrafts] = useState<DraftOrder[]>([]);
  const [garments, setGarments] = useState<GarmentTypeResponse[]>([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [searchQuery, setSearchQuery] = useState(""); // Ticket or Client
  const [garmentFilter, setGarmentFilter] = useState("");
  const [dateFilter, setDateFilter] = useState("");

  const fetchData = async () => {
    setLoading(true);
    try {
      const [ordersData, garmentsData] = await Promise.all([
        getAllOrders(),
        getAllGarments()
      ]);

      setOrders(ordersData);
      setGarments(garmentsData);

      // Fetch Drafts
      setDrafts(DraftsService.getAll());

    } catch (e) {
      console.error("Error fetching data", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleDeleteDraft = (id: string) => {
    if (confirm("¿Estás seguro de eliminar este borrador?")) {
      DraftsService.delete(id);
      setDrafts(prev => prev.filter(d => d.id !== id));
    }
  };

  // Filter Logic
  const filteredOrders = orders.filter(order => {
    // 1. Search Query (Ticket or Client Name)
    const query = searchQuery.toLowerCase();
    const matchesSearch =
      order.ticketNumber.toLowerCase().includes(query) ||
      order.customer.firstName.toLowerCase().includes(query) ||
      order.customer.lastName.toLowerCase().includes(query);

    if (!matchesSearch) return false;

    // 2. Garment Filter
    if (garmentFilter) {
      const selectedGarment = garments.find(g => g.id === garmentFilter);
      if (selectedGarment) {
        const hasGarment = order.items.some(item =>
          item.garmentName === selectedGarment.name
        );
        if (!hasGarment) return false;
      }
    }

    // 3. Date Filter (Delivery Date)
    if (dateFilter) {
      if (!order.committedDeadline) return false;
      const orderDate = order.committedDeadline.split('T')[0];
      if (orderDate !== dateFilter) return false;
    }

    return true;
  });

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-heading font-brand text-foreground">Pedidos</h1>
          <p className="text-muted-foreground">Ver y gestionar pedidos de clientes.</p>
        </div>
        <Link href="/dashboard/orders/new">
          <Button>+ Nuevo Pedido</Button>
        </Link>
      </div>

      {/* Toggle View */}
      <div className="flex bg-muted/20 p-1 rounded-xl w-fit">
        <button
          onClick={() => setView('active')}
          className={`px-6 py-2 rounded-lg text-sm font-medium transition-all ${view === 'active'
            ? 'bg-background text-foreground shadow-sm'
            : 'text-muted-foreground hover:text-foreground'
            }`}
        >
          Órdenes Activas
        </button>
        <button
          onClick={() => setView('drafts')}
          className={`px-6 py-2 rounded-lg text-sm font-medium transition-all ${view === 'drafts'
            ? 'bg-background text-foreground shadow-sm'
            : 'text-muted-foreground hover:text-foreground'
            }`}
        >
          Borradores ({drafts.length})
        </button>
      </div>

      {view === 'active' ? (
        <>
          {/* Filters */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 p-4 bg-card border border-border rounded-lg">
            <div className="col-span-2">
              <Input
                label="Buscar"
                placeholder="Ticket, Nombre del Cliente..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <div>
              <label className="text-xs font-medium mb-1 block text-muted-foreground">Filtrar por Prenda</label>
              <Select
                value={garmentFilter}
                onChange={(e) => setGarmentFilter(e.target.value)}
              >
                <option value="">Todas</option>
                {garments.map(g => (
                  <option key={g.id} value={g.id}>{g.name}</option>
                ))}
              </Select>
            </div>
            <div>
              <DatePicker
                label="Fecha de Entrega"
                value={dateFilter}
                onChange={(date) => {
                  const isoDate = date.toISOString().split('T')[0];
                  setDateFilter(isoDate);
                }}
              />
            </div>
          </div>

          <div className="bg-card border border-border rounded-xl overflow-hidden shadow-sm">
            <div className="overflow-x-auto">
              <Table className="w-full text-sm text-left">
                <TableHeader className="bg-muted/50 text-muted-foreground uppercase text-xs">
                  <TableRow>
                    <TableHead className="px-6 py-3">Ticket</TableHead>
                    <TableHead className="px-6 py-3">Cliente</TableHead>
                    <TableHead className="px-6 py-3">Prendas (Resumen)</TableHead>
                    <TableHead className="px-6 py-3">Estado</TableHead>
                    <TableHead className="px-6 py-3">Entrega</TableHead>
                    <TableHead className="px-6 py-3">Total</TableHead>
                    <TableHead className="px-6 py-3">Acción</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody className="divide-y divide-border">
                  {loading ? <TableRow><TableCell colSpan={7} className="p-4 text-center">Cargando...</TableCell></TableRow> :
                    filteredOrders.map(o => (
                      <TableRow key={o.id} className="hover:bg-muted/30 transition-colors">
                        <TableCell className="px-6 py-3 font-mono font-medium">{o.ticketNumber}</TableCell>
                        <TableCell className="px-6 py-3">{o.customer.firstName} {o.customer.lastName}</TableCell>
                        <TableCell className="px-6 py-3 text-muted-foreground text-xs max-w-[200px] truncate">
                          {o.items.map(i => i.garmentName).join(", ")}
                        </TableCell>
                        <TableCell className="px-6 py-3">
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(o.status)}`}>
                            {translateStatus(o.status)}
                          </span>
                        </TableCell>
                        <TableCell className="px-6 py-3 text-muted-foreground">
                          {formatDate(o.committedDeadline)}
                        </TableCell>
                        <TableCell className="px-6 py-3 font-medium">{formatCurrency(o.totalAmount)}</TableCell>
                        <TableCell className="px-6 py-3">
                          <div className="flex gap-2">
                            <Link href={`/dashboard/orders/${o.id}/edit`}>
                              <Button variant="ghost" size="icon" className="h-8 w-8 hover:text-primary">
                                <Edit className="w-4 h-4" />
                              </Button>
                            </Link>
                            <Link href={`/dashboard/orders/${o.id}`}>
                              <Button variant="outline" size="sm">Detalles</Button>
                            </Link>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  {!loading && filteredOrders.length === 0 && <TableRow><TableCell colSpan={7} className="p-4 text-center text-muted-foreground">No se encontraron pedidos.</TableCell></TableRow>}
                </TableBody>
              </Table>
            </div>
          </div>
        </>
      ) : (
        /* Drafts View */
        <div className="bg-card border border-border rounded-xl overflow-hidden shadow-sm">
          <div className="overflow-x-auto">
            <Table className="w-full text-sm text-left">
              <TableHeader className="bg-muted/50 text-muted-foreground uppercase text-xs">
                <TableRow>
                  <TableHead className="px-6 py-3">ID (Temporal)</TableHead>
                  <TableHead className="px-6 py-3">Cliente</TableHead>
                  <TableHead className="px-6 py-3">Prendas</TableHead>
                  <TableHead className="px-6 py-3">Última Modificación</TableHead>
                  <TableHead className="px-6 py-3 text-right">Acciones</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody className="divide-y divide-border">
                {drafts.length === 0 ? (
                  <TableRow><TableCell colSpan={5} className="p-8 text-center text-muted-foreground">No hay borradores guardados</TableCell></TableRow>
                ) : (
                  drafts.map(d => (
                    <TableRow key={d.id} className="hover:bg-muted/30 transition-colors">
                      <TableCell className="px-6 py-3 font-mono text-xs">{d.id.slice(0, 8)}...</TableCell>
                      <TableCell className="px-6 py-3 font-medium">
                        {d.customer?.firstName ? `${d.customer.firstName} ${d.customer.lastName || ''}` : <span className="text-muted-foreground italic">Sin nombre</span>}
                      </TableCell>
                      <TableCell className="px-6 py-3">
                        {d.items?.length || 0} prendas
                      </TableCell>
                      <TableCell className="px-6 py-3 text-muted-foreground">
                        {new Date(d.lastModified).toLocaleString()}
                      </TableCell>
                      <TableCell className="px-6 py-3 text-right">
                        <div className="flex justify-end gap-2">
                          <Link href={`/dashboard/orders/new?draftId=${d.id}`}>
                            <Button variant="ghost" size="icon" className="h-8 w-8 hover:text-primary">
                              <Edit className="w-4 h-4" />
                            </Button>
                          </Link>
                          <Button variant="ghost" size="icon" className="h-8 w-8 hover:text-destructive" onClick={() => handleDeleteDraft(d.id)}>
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </div>
      )}
    </div>
  );
}
