// anotame-web/src/routes/(app)/dashboard/catalog/pricelists/[id]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { apiService, API_CATALOG } from '$lib/services/api.svelte';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import * as Form from '$lib/components/ui/form';
  import { Checkbox } from '$lib/components/ui/checkbox';
  import { AdaptiveDatePicker } from '$lib/components/ui/responsive';
  import * as Card from '$lib/components/ui/card';
  import { ResponsiveDataView } from '$lib/components/common';
  import type { ColumnDef, Row } from '@tanstack/table-core';
  import type { ServiceResponse, PriceListResponse, PriceListItemDto } from '$lib/types/dtos';
  import { adaptiveConfirm } from '$lib/components/ui/responsive/confirm-state.svelte';
  import { toast } from 'svelte-sonner';
  import { Loader2 } from '@lucide/svelte';
  import * as m from '$lib/paraglide/messages';
  import { superForm, defaults } from 'sveltekit-superforms';
  import { zod4 } from 'sveltekit-superforms/adapters';
  import { z } from 'zod';

  // Derived ID
  let listId = $derived($page.params.id);


  // State
  let isLoading = $state(true);
  let isSaving = $state(false);
  let services = $state<ServiceResponse[]>([]);

  const pricelistSchema = z.object({
    name: z.string().min(1, m["catalog.pricelist.zodNameRequired"]()),
    priority: z.number().default(0),
    validFrom: z.string().min(1, m["catalog.pricelist.zodValidFromRequired"]()),
    validTo: z.string().optional().or(z.literal('')),
    active: z.boolean().default(true),
  });

  // Overrides Map: ServiceID -> String Price
  let overrides = $state<Record<string, string>>({});

  // Original state reference for resets
  let originalOverrides = $state<Record<string, string>>({});

  const superform = superForm(defaults(zod4(pricelistSchema)), {
    id: 'pricelist-edit-form',
    SPA: true,
    validators: zod4(pricelistSchema),
    async onUpdate({ form: f }) {
      if (!f.valid) return;

      isSaving = true;
      try {
        const items = Object.entries(overrides)
          .filter(([_, val]) => val !== null && val !== undefined && String(val).trim() !== '')
          .map(([serviceId, val]) => ({
            serviceId,
            price: parseFloat(String(val))
          }));

        const payload = {
          name: f.data.name,
          priority: f.data.priority,
          validFrom: new Date(f.data.validFrom).toISOString(),
          validTo: f.data.validTo ? new Date(f.data.validTo).toISOString() : null,
          active: f.data.active,
          items
        };

        await apiService.request(`${API_CATALOG}/pricelists/${listId}`, {
          method: 'PUT',
          body: JSON.stringify(payload)
        });

        toast.success(m["catalog.pricelist.updateSuccess"]());
        await goto('/dashboard/catalog/pricelists');
      } catch (err: any) {
        toast.error(err.message || m["catalog.pricelist.updateError"]());
      } finally {
        isSaving = false;
      }
    }
  });

  const { form, enhance } = superform;

  // Column definitions for overrides table
  const overrideColumns: ColumnDef<ServiceResponse>[] = [
    {
      accessorKey: 'name',
      header: m["catalog.pricelist.columnService"](),
      enableSorting: false,
      meta: { cardGroup: 'header' },
    },
    {
      accessorKey: 'basePrice',
      header: m["catalog.pricelist.columnBasePrice"](),
      enableSorting: false,
      accessorFn: (row) => `$${row.basePrice.toFixed(2)}`,
      meta: { cardGroup: 'body' },
    },
    {
      id: 'override',
      header: m["catalog.pricelist.columnOverride"](),
      enableSorting: false,
      meta: { cardGroup: 'body' },
    },
  ];

  onMount(async () => {
    try {
      // Fetch both services and the specific pricelist simultaneously
      const [svcRes, listRes] = await Promise.all([
        apiService.request<ServiceResponse[]>(`${API_CATALOG}/catalog/services`),
        apiService.request<PriceListResponse>(`${API_CATALOG}/pricelists/${listId}`)
      ]);

      services = svcRes || [];

      const list = listRes;
      if (list) {
        $form.name = list.name;
        $form.priority = list.priority;
        $form.active = list.active;
        if (list.validFrom) $form.validFrom = new Date(list.validFrom).toISOString().split('T')[0];
        if (list.validTo) $form.validTo = new Date(list.validTo).toISOString().split('T')[0];

        const newOverrides: Record<string, string> = {};
        if (list.items) {
          list.items.forEach((item: PriceListItemDto) => {
            newOverrides[item.serviceId] = String(item.price);
          });
        }
        overrides = newOverrides;
        originalOverrides = { ...newOverrides };
      }
    } catch (err: any) {
      toast.error(err.message || m["catalog.pricelist.loadError"]());
      goto('/dashboard/catalog/pricelists');
    } finally {
      isLoading = false;
    }
  });

  function handleBulkAdjustment(amount: number) {
    let next: Record<string, string> = { ...overrides };
    services.forEach(service => {
      const currentPrice = parseFloat(next[service.id] || String(service.basePrice));
      const newPrice = Math.max(0, currentPrice + amount);
      next[service.id] = newPrice.toFixed(2);
    });
    overrides = next;
    toast.success(m["catalog.pricelist.bulkAdjustSuccess"]({ sign: amount > 0 ? '+' : '', amount }));
  }

  function handleReset() {
    overrides = { ...originalOverrides };
    toast.info(m["catalog.pricelist.resetSuccess"]());
  }
</script>

{#if isLoading}
  <div class="h-64 flex items-center justify-center text-muted-foreground animate-pulse">
    {m["catalog.pricelist.loadingStrategy"]()}
  </div>
{:else}
  {#snippet overrideCellRender(row: Row<ServiceResponse>)}
    <Input
      type="number"
      step="0.01"
      min="0"
      class="h-12 w-full max-w-45 mx-auto text-center font-mono font-bold text-primary shadow-sm bg-background"
      placeholder={m["catalog.pricelist.overridePlaceholder"]()}
      bind:value={overrides[row.original.id]}
    />
  {/snippet}

  {@const cellRenders = {
    override: overrideCellRender
  }}

  <div class="max-w-4xl w-full min-w-0 mx-auto space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
    <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
      <div class="min-w-0">
        <h1 class="text-3xl font-heading font-bold text-foreground">{m["catalog.pricelist.editTitle"]()}</h1>
        <p class="text-muted-foreground wrap-break-word">{m["catalog.pricelist.editSubtitle"]({ name: $form.name })}</p>
      </div>
      <Button variant="outline" class="h-11 w-full sm:w-auto touch-manipulation" onclick={() => goto('/dashboard/catalog/pricelists')}>{m["common.cancel"]()}</Button>
    </div>

    <form method="POST" use:enhance class="space-y-6">
      <Card.Root>
        <Card.Header>
          <Card.Title>{m["catalog.pricelist.detailsCardTitle"]()}</Card.Title>
        </Card.Header>
        <Card.Content class="space-y-4">
          <Form.Field form={superform} name="name">
            {#snippet children({ constraints })}
              <Form.Control>
                {#snippet children({ props })}
                  <Form.Label>{m["catalog.pricelist.nameLabel"]()} <span class="text-destructive">*</span></Form.Label>
                  <Input {...props} {...constraints} placeholder={m["catalog.pricelist.namePlaceholder"]()} bind:value={$form.name} class="h-12" />
                {/snippet}
              </Form.Control>
              <Form.FieldErrors />
            {/snippet}
          </Form.Field>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Form.Field form={superform} name="priority">
              {#snippet children({ constraints })}
                <Form.Control>
                  {#snippet children({ props })}
                    <Form.Label>{m["catalog.pricelist.priorityLabel"]()}</Form.Label>
                    <Input {...props} {...constraints} type="number" bind:value={$form.priority} class="h-12 font-mono" />
                  {/snippet}
                </Form.Control>
                <Form.FieldErrors />
              {/snippet}
            </Form.Field>

            <Form.Field form={superform} name="active">
              {#snippet children()}
                <Form.Control>
                  {#snippet children({ props })}
                    <div class="flex items-center gap-3 pt-8">
                      <Checkbox {...props} class="size-5" bind:checked={$form.active} />
                      <Form.Label class="flex min-h-11 items-center font-medium cursor-pointer touch-manipulation">
                        {m["catalog.pricelist.activeLabel"]()}
                      </Form.Label>
                    </div>
                  {/snippet}
                </Form.Control>
                <Form.FieldErrors />
              {/snippet}
            </Form.Field>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Form.Field form={superform} name="validFrom">
              {#snippet children({ constraints })}
                <Form.Label>{m["catalog.pricelist.validFromLabel"]()}</Form.Label>
                <AdaptiveDatePicker id="pl-from" bind:value={$form.validFrom} />
                <Form.FieldErrors />
              {/snippet}
            </Form.Field>
            <Form.Field form={superform} name="validTo">
              {#snippet children({ constraints })}
                <Form.Label>{m["catalog.pricelist.validToLabel"]()}</Form.Label>
                <AdaptiveDatePicker id="pl-to" value={$form.validTo ?? ''} onValueChange={(v) => $form.validTo = v} placeholder={m["catalog.pricelist.validToPlaceholder"]()} />
                <Form.FieldErrors />
              {/snippet}
            </Form.Field>
          </div>
        </Card.Content>
      </Card.Root>

      <Card.Root>
        <Card.Header>
          <Card.Title>{m["catalog.pricelist.overridesCardTitle"]()}</Card.Title>
          <Card.Description>{m["catalog.pricelist.overridesCardDescription"]()}</Card.Description>
        </Card.Header>
        <Card.Content class="space-y-4">
          <!-- Bulk adjustments -->
          <div class="flex flex-col sm:flex-row flex-wrap gap-2 items-center p-4 bg-secondary/20 rounded-lg border border-border">
            <span class="text-sm font-bold mr-2 uppercase tracking-wide opacity-70">{m["catalog.pricelist.bulkAdjust"]()}</span>
            <div class="flex gap-2">
              {#each [5, 10, 15, 20] as amount (amount)}
                <Button type="button" variant="outline" size="sm" class="font-mono text-success-text hover:text-success-text hover:bg-success/10 border-success/30 touch-manipulation h-11" onclick={() => handleBulkAdjustment(amount)}>
                  +${amount}
                </Button>
              {/each}
            </div>
            <div class="hidden sm:block w-px h-6 bg-border mx-2"></div>
            <div class="flex gap-2">
              {#each [5, 10, 15, 20] as amount (amount)}
                <Button type="button" variant="outline" size="sm" class="font-mono text-destructive hover:text-destructive hover:bg-destructive/10 border-destructive/30 touch-manipulation h-11" onclick={() => handleBulkAdjustment(-amount)}>
                  -${amount}
                </Button>
              {/each}
            </div>
            <div class="w-full sm:w-px sm:h-6 bg-border mx-0 sm:mx-2 my-2 sm:my-0"></div>
            <Button type="button" variant="ghost" size="sm" class="h-11 text-muted-foreground w-full sm:w-auto" onclick={handleReset}>
              {m["catalog.pricelist.restoreButton"]()}
            </Button>
          </div>

          <!-- Overrides Table -->
          <div class="border rounded-md overflow-x-auto">
            <ResponsiveDataView
              columns={overrideColumns}
              data={services}
              loading={false}
              emptyMessage={m["catalog.pricelist.noServices"]()}
              {cellRenders}
            />
          </div>
        </Card.Content>
      </Card.Root>

      <div class="flex flex-col-reverse sm:flex-row sm:justify-between sm:items-center gap-4 pt-4 pb-12">
        <Button
          type="button"
          variant="ghost"
          class="h-14 w-full sm:w-auto px-8 text-lg touch-manipulation text-destructive hover:bg-destructive-muted hover:text-destructive"
          onclick={async () => {
            const ok = await adaptiveConfirm({
              title: m["catalog.pricelist.discardTitle"](),
              description: m["catalog.pricelist.discardDescription"]()
            });
            if(ok) goto('/dashboard/catalog/pricelists');
          }}
        >
          {m["catalog.pricelist.discardChanges"]()}
        </Button>
        <Button type="submit" disabled={isSaving} class="h-14 w-full sm:w-auto px-8 text-lg shadow-md touch-manipulation">
          {#if isSaving}
            <Loader2 class="w-4 h-4 mr-2 animate-spin" />
            {m["catalog.pricelist.saving"]()}
          {:else}
            {m["catalog.pricelist.saveStrategyButton"]()}
          {/if}
        </Button>
      </div>
    </form>
  </div>
{/if}

// anotame-web/src/app/dashboard/catalog/pricelists/[id]/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { DatePicker } from "@/components/ui/DatePicker";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { updatePriceList, getPriceList } from "@/services/catalog/pricelists";
import { getServices } from "@/services/catalog/services";
import { ServiceResponse, PriceListResponse } from "@/types/dtos";

export default function EditPriceListPage() {
    const router = useRouter();
    const params = useParams();
    const id = params?.id as string;
    const [isLoading, setIsLoading] = useState(true);
    const [services, setServices] = useState<ServiceResponse[]>([]);

    // Form State
    const [name, setName] = useState("");
    const [priority, setPriority] = useState(0);
    const [validFrom, setValidFrom] = useState(new Date().toISOString().split('T')[0]);
    const [validTo, setValidTo] = useState("");
    const [active, setActive] = useState(true);

    // Overrides: Map of ServiceID -> Price
    const [overrides, setOverrides] = useState<Record<string, string>>({});
    const [initialOverrides, setInitialOverrides] = useState<Record<string, string>>({});

    useEffect(() => {
        if (!id) return;
        const loadData = async () => {
            try {
                const [servicesData, listData] = await Promise.all([
                    getServices(),
                    getPriceList(id)
                ]);
                setServices(servicesData);

                // Populate Form
                setName(listData.name);
                setPriority(listData.priority);
                setValidFrom(new Date(listData.validFrom).toISOString().split('T')[0]);
                if (listData.validTo) {
                    setValidTo(new Date(listData.validTo).toISOString().split('T')[0]);
                }
                setActive(listData.active);

                // Populate Overrides
                if (listData.items) {
                    const initialOverrides: Record<string, string> = {};
                    listData.items.forEach(item => {
                        initialOverrides[item.serviceId] = String(item.price);
                    });
                    setOverrides(initialOverrides);
                    setInitialOverrides(initialOverrides);
                }
            } catch (error) {
                console.error("Failed to load data", error);
                alert("Failed to load price list");
                router.push("/dashboard/catalog/pricelists");
            } finally {
                setIsLoading(false);
            }
        };
        loadData();
    }, [id, router]);

    const handleReset = () => {
        setOverrides(initialOverrides);
    };

    const handleBulkAdjustment = (amount: number) => {
        setOverrides(prev => {
            const next = { ...prev };
            services.forEach(service => {
                const currentPrice = parseFloat(next[service.id] || String(service.basePrice));
                const newPrice = Math.max(0, currentPrice + amount);
                next[service.id] = newPrice.toFixed(2);
            });
            return next;
        });
    };

    const handleOverrideChange = (serviceId: string, val: string) => {
        setOverrides(prev => ({ ...prev, [serviceId]: val }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);

        try {
            // Filter out empty overrides
            const items = Object.entries(overrides)
                .filter(([key, val]) => val && val.trim() !== "")
                .map(([serviceId, val]) => ({
                    serviceId,
                    price: parseFloat(val)
                }));

            const payload = {
                name,
                priority,
                validFrom: new Date(validFrom).toISOString(),
                validTo: validTo ? new Date(validTo).toISOString() : undefined,
                active,
                items
            };
            await updatePriceList(id, payload);

            router.push("/dashboard/catalog/pricelists");
        } catch (err) {
            console.error(err);
            alert("Failed to update price list");
        } finally {
            setIsLoading(false);
        }
    };

    if (isLoading) return <div className="p-8 text-center">Loading...</div>;

    return (
        <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-3xl font-bold">Edit Price List</h1>
                <Button variant="outline" onClick={() => router.back()}>Cancel</Button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
                <Card>
                    <CardHeader>
                        <CardTitle>Strategy Details</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <Input label="Name" placeholder="e.g. Winter Sale 2025" required value={name} onChange={e => setName(e.target.value)} />
                        <div className="grid grid-cols-2 gap-4">
                            <Input label="Priority (Higher wins)" type="number" required value={priority} onChange={e => setPriority(parseInt(e.target.value))} />
                            <div className="flex items-center gap-2 pt-8">
                                <input type="checkbox" className="w-5 h-5" checked={active} onChange={e => setActive(e.target.checked)} />
                                <label>Is Active</label>
                            </div>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <DatePicker
                                label="Valid From"
                                value={validFrom}
                                onChange={date => setValidFrom(date.toISOString().split('T')[0])}
                            />
                            <DatePicker
                                label="Valid To (Optional)"
                                value={validTo}
                                onChange={date => setValidTo(date.toISOString().split('T')[0])}
                            />
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle>Price Overrides</CardTitle>
                        <p className="text-sm text-muted-foreground">Values here override the Service Base Price.</p>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="flex flex-wrap gap-2 items-center p-4 bg-secondary/10 rounded-lg border border-border">
                            <span className="text-sm font-medium mr-2">Bulk Adjust:</span>
                            {[5, 10, 15, 20].map(amount => (
                                <Button key={`plus-${amount}`} type="button" variant="outline" size="sm" onClick={() => handleBulkAdjustment(amount)} className="text-green-600 hover:text-green-700 hover:bg-green-50 border-green-200">
                                    + ${amount}
                                </Button>
                            ))}
                            <div className="w-px h-6 bg-border mx-2" />
                            {[5, 10, 15, 20].map(amount => (
                                <Button key={`minus-${amount}`} type="button" variant="outline" size="sm" onClick={() => handleBulkAdjustment(-amount)} className="text-red-600 hover:text-red-700 hover:bg-red-50 border-red-200">
                                    - ${amount}
                                </Button>
                            ))}
                            <div className="w-px h-6 bg-border mx-2" />
                            <Button type="button" variant="ghost" size="sm" onClick={handleReset} className="text-muted-foreground hover:text-foreground">
                                Reset
                            </Button>
                        </div>

                        <div className="border rounded-md">
                            <table className="w-full text-sm">
                                <thead className="bg-secondary/20">
                                    <tr>
                                        <th className="p-3 text-left">Service</th>
                                        <th className="p-3 text-left">Base Price</th>
                                        <th className="p-3 text-left">Override Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {services.map(service => (
                                        <tr key={service.id} className="border-t hover:bg-secondary/5">
                                            <td className="p-3 font-medium">{service.name}</td>
                                            <td className="p-3 text-muted-foreground">${service.basePrice.toFixed(2)}</td>
                                            <td className="p-3">
                                                <Input
                                                    placeholder="e.g. 100.00"
                                                    type="number"
                                                    step="0.01"
                                                    value={overrides[service.id] || ""}
                                                    onChange={e => handleOverrideChange(service.id, e.target.value)}
                                                />
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </CardContent>
                </Card>

                <div className="flex justify-end gap-4">
                    <Button type="submit" disabled={isLoading} size="lg">
                        {isLoading ? "Saving..." : "Save Changes"}
                    </Button>
                </div>
            </form>
        </div>
    );
}
