// anotame-web/src/app/dashboard/orders/[id]/page.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { API_SALES } from "@/lib/api";
import { OrderResponse, Establishment } from "@/types/dtos";
import { getSettings } from "@/services/operations/establishment";
import { generateReceiptHtml } from "@/utils/receipt-generator";
import { translateStatus, getBadgeVariant } from "@/utils/statusUtils";
import { formatCurrency, formatDateTime } from "@/utils/formatUtils";
import { Badge } from "@/components/ui/Badge";



export default function OrderDetailsPage({ params, searchParams }: {
  params: Promise<{ id: string }>,
  searchParams?: Promise<{ [key: string]: string | string[] | undefined }>
}) {
  const router = useRouter();
  const [order, setOrder] = useState<OrderResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [establishment, setEstablishment] = useState<Establishment | null>(null);

  useEffect(() => {
    getSettings().then(setEstablishment).catch(console.error);
  }, []);

  const [id, setId] = useState<string | null>(null);
  const [action, setAction] = useState<string | null>(null);

  useEffect(() => {
    params.then(p => setId(p.id));
    if (searchParams) {
      searchParams.then(sp => {
        if (sp && sp.action) setAction(sp.action as string);
      });
    }
  }, [params, searchParams]);

  useEffect(() => {
    if (!id) return;

    const fetchOrder = async () => {
      try {
        const res = await fetch(`${API_SALES}/orders/${id}`);
        if (res.ok) {
          const data = await res.json();
          setOrder(data);
        }
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    fetchOrder();
  }, [id]);

  // Handle auto-print action
  useEffect(() => {
    if (action === 'print' && order && establishment && !loading) {
      // Clear action to prevent double prompt
      setAction(null);
      // Remove query param from URL without reload
      window.history.replaceState(null, '', `/dashboard/orders/${id}`);

      // Small timeout to let UI render completely
      setTimeout(() => {
        if (confirm("Pedido creado con éxito. ¿Deseas imprimir el ticket ahora?")) {
          handlePrint();
        }
      }, 500);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [action, order, establishment, loading, id]);

  const handleCancel = async () => {
    if (!order || !confirm("¿Estás seguro que deseas cancelar este pedido?")) return;
    try {
      const res = await fetch(`${API_SALES}/orders/${order.id}`, { method: "DELETE" });
      if (res.ok) {
        alert("Pedido cancelado");
        router.push("/dashboard/orders");
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handlePrint = () => {
    if (!order) return;

    const receiptHtml = generateReceiptHtml({
      ticketNumber: order.ticketNumber,
      customerName: `${order.customer.firstName} ${order.customer.lastName}`,
      phone: order.customer.phoneNumber,
      deadline: order.committedDeadline || new Date().toISOString(),
      items: order.items.map(i => ({
        garment: i.garmentName,
        services: i.services?.map(s => ({
          name: s.serviceName,
          price: s.unitPrice,
          adjustment: s.adjustmentAmount,
          adjustmentReason: s.adjustmentReason
        })) || [],
        notes: i.notes,
      })),
      total: order.totalAmount,
      amountPaid: order.amountPaid || 0,
      balance: Math.max(0, (order.totalAmount || 0) - (order.amountPaid || 0)),
      establishment: {
        name: establishment?.name || "ANOTAME",
        address: establishment?.taxInfo ? JSON.parse(establishment.taxInfo).address : undefined,
        rfc: establishment?.taxInfo ? JSON.parse(establishment.taxInfo).rfc : undefined,
        taxRegime: establishment?.taxInfo ? JSON.parse(establishment.taxInfo).regime : undefined,
        contactPhone: establishment?.taxInfo ? JSON.parse(establishment.taxInfo).contactPhone : undefined,
      }
    });

    const newWindow = window.open('', '_blank', 'width=400,height=600');
    if (newWindow) {
      newWindow.document.write(receiptHtml);
      newWindow.document.close();
      newWindow.setTimeout(() => {
        newWindow.focus();
        newWindow.print();
        newWindow.close();
      }, 250);
    }
  };

  const handleSendToOps = async () => {
    if (!order || !confirm("¿Enviar pedido a Operaciones? El estado cambiará a EN PROGRESO.")) return;
    try {
      const res = await fetch(`${API_SALES}/orders/${order.id}/status`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ status: "IN_PROGRESS" })
      });

      if (res.ok) {
        alert("¡Pedido enviado a Operaciones!");
        setLoading(true);
        const newRes = await fetch(`${API_SALES}/orders/${id}`);
        if (newRes.ok) setOrder(await newRes.json());
        setLoading(false);
      } else {
        alert("Error al actualizar estado.");
      }
    } catch (e) {
      console.error(e);
      alert("Error de conexión");
    }
  };

  if (!id || loading) return <div className="p-8">Cargando...</div>;
  if (!order) return <div className="p-8">Pedido no encontrado</div>;

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center gap-4">
        <Link href="/dashboard/orders" className="text-muted-foreground hover:text-foreground">
          ← Atrás
        </Link>
        <h1 className="text-2xl font-bold font-heading">Pedido {order.ticketNumber}</h1>
        <Badge variant={getBadgeVariant(order.status)}>
          {translateStatus(order.status)}
        </Badge>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Customer Info */}
        <div className="bg-card p-6 rounded-xl border border-border">
          <h3 className="font-semibold mb-4 text-lg">Cliente</h3>
          <div className="space-y-2 text-sm">
            <p><span className="text-muted-foreground">Nombre:</span> {order.customer.firstName} {order.customer.lastName}</p>
            <p><span className="text-muted-foreground">Correo:</span> {order.customer.email}</p>
            <p><span className="text-muted-foreground">Teléfono:</span> {order.customer.phoneNumber || "-"}</p>
          </div>
        </div>

        {/* Order Info & Payment */}
        <div className="bg-card p-6 rounded-xl border border-border">
          <h3 className="font-semibold mb-4 text-lg">Detalles del Pedido</h3>
          <div className="space-y-3 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Creado:</span>
              <span>{new Date(order.createdAt).toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Entrega Estimada:</span>
              <span className="font-medium">{formatDateTime(order.committedDeadline)}</span>
            </div>

            <div className="h-px bg-border my-2" />

            <div className="flex justify-between">
              <span className="text-muted-foreground">Método de Pago:</span>
              <span className="font-medium">{order.paymentMethod === 'CASH' ? 'Efectivo' : order.paymentMethod === 'CARD' ? 'Tarjeta' : order.paymentMethod === 'TRANSFER' ? 'Transferencia' : order.paymentMethod || '-'}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Total:</span>
              <span className="font-medium">{formatCurrency(order.totalAmount)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">A cuenta:</span>
              <span className="font-medium text-success">-{formatCurrency(order.amountPaid)}</span>
            </div>
            <div className="border-t border-border pt-2 flex justify-between items-center">
              <span className="font-bold">Saldo Pendiente:</span>
              <span className={`text-xl font-bold ${((order.totalAmount || 0) - (order.amountPaid || 0)) > 0.01 ? 'text-destructive' : 'text-success'}`}>
                {formatCurrency(Math.max(0, (order.totalAmount || 0) - (order.amountPaid || 0)))}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Order Notes */}
      {order.notes && (
        <div className="bg-warning/10 p-4 rounded-xl border border-warning/20 text-warning-foreground">
          <h3 className="font-semibold mb-1 text-sm uppercase tracking-wide opacity-70">Notas Generales</h3>
          <p className="text-sm font-medium">{order.notes}</p>
        </div>
      )}

      {/* Items */}
      <div className="bg-card border border-border rounded-xl overflow-hidden">
        <div className="p-4 border-b border-border font-semibold">Prendas y Servicios</div>
        <table className="w-full text-sm text-left">
          <thead className="bg-muted/50 text-muted-foreground uppercase text-xs">
            <tr>
              <th className="px-6 py-3">Descripción</th>
              <th className="px-6 py-3">Servicio</th>
              <th className="px-6 py-3">Cant</th>
              <th className="px-6 py-3">Precio</th>
              <th className="px-6 py-3">Subtotal</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {order.items.map(item => (
              <tr key={item.id}>
                <td className="px-6 py-3">
                  <div className="font-bold">{item.garmentName}</div>
                  {item.notes && <div className="text-xs text-muted-foreground mt-1 bg-muted/30 p-1 rounded inline-block"> Nota: {item.notes}</div>}
                </td>
                <td colSpan={3} className="px-0 py-0">
                  <table className="w-full">
                    <tbody className="divide-y divide-border/50">
                      {item.services?.map((service, idx) => (
                        <tr key={idx}>
                          <td className="px-6 py-2 w-1/3 text-muted-foreground">{service.serviceName}</td>
                          <td className="px-6 py-2 w-1/3 text-center">{item.quantity}</td>
                          <td className="px-6 py-2 w-1/3">
                            <div>${service.unitPrice}</div>
                            {service.adjustmentAmount && service.adjustmentAmount !== 0 ? (
                              <div className={`text-xs ${service.adjustmentAmount > 0 ? 'text-destructive' : 'text-success'}`}>
                                {service.adjustmentAmount > 0 ? '+' : ''}{service.adjustmentAmount}
                                {service.adjustmentReason && ` (${service.adjustmentReason})`}
                              </div>
                            ) : null}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </td>
                <td className="px-6 py-3 font-medium align-top pt-4">${item.subtotal}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Actions */}
      <div className="flex justify-between pt-4 border-t border-border">
        <button
          onClick={handleCancel}
          className="px-4 py-2 text-destructive hover:bg-destructive/10 rounded-lg font-medium transition-colors"
        >
          Cancelar Pedido
        </button>

        <div className="flex gap-3">
          <Link href={`/dashboard/orders/${order.id}/edit`}>
            <button
              className="px-4 py-2 border border-input hover:bg-accent hover:text-accent-foreground rounded-lg font-medium"
            >
              Editar Pedido
            </button>
          </Link>
          <button
            onClick={handlePrint}
            className="px-4 py-2 border border-input hover:bg-accent hover:text-accent-foreground rounded-lg font-medium"
          >
            Imprimir Ticket
          </button>
          {order.status === 'RECEIVED' && (
            <button
              onClick={handleSendToOps}
              className="px-4 py-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg font-medium shadow-sm"
            >
              Enviar a Operaciones
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

// anotame-web/src/routes/(app)/dashboard/orders/[id]/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import { apiService, API_SALES, API_OPERATIONS } from "$lib/services/api.svelte";
  import { generateReceiptHtml } from "$lib/utils/receipt-generator";
  import { translateStatus, getStatusColor } from "$lib/utils/statusUtils";
  import { formatCurrency, formatDateTime } from "$lib/utils/formatUtils";
  import { Button } from "$lib/components/ui/button";
  import * as Table from "$lib/components/ui/table";
  import { toast } from "svelte-sonner";
  import { adaptiveConfirm } from "$lib/components/ui/responsive/confirm-state.svelte";

  let id = $derived($page.params.id);
  let action = $derived($page.url.searchParams.get("action"));

  let order = $state<any | null>(null);
  let loading = $state(true);
  let establishment = $state<any | null>(null);

  onMount(async () => {
    try {
      const res = await apiService.request<any>(`${API_OPERATIONS}/settings/establishment`);
      establishment = res;
    } catch (e) {
      console.error(e);
    }
  });

  // Watch for ID changes to fetch order
  $effect(() => {
    if (!id) return;
    
    let isCancelled = false;
    const fetchOrder = async () => {
      try {
        loading = true;
        const res = await apiService.request<any>(`${API_SALES}/orders/${id}`);
        if (!isCancelled) order = res;
      } catch (e) {
        console.error(e);
      } finally {
        if (!isCancelled) loading = false;
      }
    };
    fetchOrder();

    return () => { isCancelled = true; };
  });

  // Handle auto-print action
  $effect(() => {
    if (action === 'print' && order && establishment && !loading) {
      const url = new URL(window.location.href);
      url.searchParams.delete('action');
      window.history.replaceState(null, '', url.toString());

      setTimeout(async () => {
        const ok = await adaptiveConfirm({
          title: '¡Pedido Creado!',
          description: 'Pedido creado con éxito. ¿Deseas imprimir el ticket ahora?'
        });
        if (ok) handlePrint();
      }, 500);
    }
  });

  async function handleCancel() {
    if (!order) return;
    const ok = await adaptiveConfirm({
      title: 'Cancelar Pedido',
      description: '¿Estás seguro que deseas cancelar este pedido? Esta acción no se puede deshacer.'
    });
    if (!ok) return;
    try {
      await apiService.request(`${API_SALES}/orders/${order.id}`, { method: "DELETE" });
      toast.success("Pedido cancelado exitosamente");
      goto("/dashboard/orders");
    } catch (e: any) {
      console.error(e);
      if (e?.message?.includes('409')) {
        toast.error('No se puede eliminar', {
          description: 'El pedido tiene órdenes de trabajo asociadas. Elimina las órdenes de trabajo primero.'
        });
      } else {
        toast.error('Error al cancelar pedido', { description: e?.message });
      }
    }
  }

  function handlePrint() {
    if (!order) return;

    let taxInfoParsed: any = undefined;
    if (establishment?.taxInfo) {
      try { taxInfoParsed = JSON.parse(establishment.taxInfo); } catch(e){}
    }

    const receiptHtml = generateReceiptHtml({
      ticketNumber: order.ticketNumber,
      customerName: `${order.customer.firstName} ${order.customer.lastName}`,
      phone: order.customer.phoneNumber,
      deadline: order.committedDeadline || new Date().toISOString(),
      items: order.items.map((i: any) => ({
        garment: i.garmentName,
        services: i.services?.map((s: any) => ({
          name: s.serviceName,
          price: s.unitPrice,
          adjustment: s.adjustmentAmount,
          adjustmentReason: s.adjustmentReason
        })) || [],
        notes: i.notes,
      })),
      total: order.totalAmount,
      amountPaid: order.amountPaid || 0,
      balance: Math.max(0, (order.totalAmount || 0) - (order.amountPaid || 0)),
      establishment: {
        name: establishment?.name || "ANOTAME",
        address: taxInfoParsed?.address,
        rfc: taxInfoParsed?.rfc,
        taxRegime: taxInfoParsed?.regime,
        contactPhone: taxInfoParsed?.contactPhone,
      }
    });

    const newWindow = window.open('', '_blank', 'width=400,height=600');
    if (newWindow) {
      newWindow.document.write(receiptHtml);
      newWindow.document.close();
      newWindow.setTimeout(() => {
        newWindow.focus();
        newWindow.print();
        newWindow.close();
      }, 250);
    }
  }

  async function handleSendToOps() {
    if (!order) return;
    const ok = await adaptiveConfirm({
      title: 'Enviar a Operaciones',
      description: '¿Enviar pedido a Operaciones? El estado cambiará a EN PROGRESO.'
    });
    if (!ok) return;
    try {
      await apiService.request(`${API_SALES}/orders/${order.id}/status`, {
        method: "PATCH",
        body: JSON.stringify({ status: "IN_PROGRESS" })
      });
      
      toast.success("¡Pedido enviado a Operaciones!");
      loading = true;
      const res = await apiService.request<any>(`${API_SALES}/orders/${id}`);
      order = res;
    } catch (e: any) {
      console.error(e);
      toast.error("Error de conexión", { description: e.message });
    } finally {
      loading = false;
    }
  }
</script>

{#if !id || loading}
  <div class="p-8 text-center text-muted-foreground animate-pulse">Cargando pedido...</div>
{:else if !order}
  <div class="p-8 text-center text-destructive font-bold text-lg">Pedido no encontrado</div>
{:else}
  <div class="space-y-6 max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-300 pb-20">
    <div class="flex items-center gap-4">
      <a href="/dashboard/orders" class="text-muted-foreground hover:text-foreground touch-manipulation">
        &larr; Atrás
      </a>
      <h1 class="text-2xl font-bold">Pedido {order.ticketNumber}</h1>
      <span class={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide border border-border/50 shadow-sm ${getStatusColor(order.status)}`}>
        {translateStatus(order.status)}
      </span>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <!-- Customer Info -->
      <div class="bg-card p-6 rounded-2xl border border-border shadow-sm">
        <h3 class="font-bold mb-4 text-lg">Cliente</h3>
        <div class="space-y-3 text-sm">
          <p><span class="text-muted-foreground mr-2 font-medium">Nombre:</span> <span class="font-semibold">{order.customer.firstName} {order.customer.lastName}</span></p>
          <p><span class="text-muted-foreground mr-2 font-medium">Correo:</span> {order.customer.email}</p>
          <p><span class="text-muted-foreground mr-2 font-medium">Teléfono:</span> {order.customer.phoneNumber || "-"}</p>
        </div>
      </div>

      <!-- Order Info & Payment -->
      <div class="bg-card p-6 rounded-2xl border border-border shadow-sm">
        <h3 class="font-bold mb-4 text-lg">Detalles del Pedido</h3>
        <div class="space-y-3 text-sm">
          <div class="flex justify-between items-center">
            <span class="text-muted-foreground font-medium">Creado:</span>
            <span class="font-mono bg-secondary/30 px-2 py-1 rounded">{new Date(order.createdAt).toLocaleString()}</span>
          </div>
          <div class="flex justify-between items-center">
            <span class="text-muted-foreground font-medium">Entrega Estimada:</span>
            <span class="font-medium bg-primary/10 text-primary px-2 py-1 rounded border border-primary/20">{formatDateTime(order.committedDeadline)}</span>
          </div>

          <div class="h-px bg-border my-4"></div>

          <div class="flex justify-between items-center">
            <span class="text-muted-foreground font-medium">Método de Pago:</span>
            <span class="font-bold text-foreground">
              {order.paymentMethod === 'CASH' ? 'Efectivo' : order.paymentMethod === 'CARD' ? 'Tarjeta' : order.paymentMethod === 'TRANSFER' ? 'Transferencia' : order.paymentMethod || '-'}
            </span>
          </div>
          <div class="flex justify-between items-center">
            <span class="text-muted-foreground font-medium">Total:</span>
            <span class="font-medium text-lg">{formatCurrency(order.totalAmount)}</span>
          </div>
          <div class="flex justify-between items-center">
            <span class="text-muted-foreground font-medium">A cuenta:</span>
            <span class="font-bold text-success text-lg">-{formatCurrency(order.amountPaid)}</span>
          </div>
          <div class="border-t border-border pt-3 mt-1 flex justify-between items-center">
            <span class="font-bold uppercase tracking-wider text-muted-foreground">Saldo Pendiente:</span>
            <span class={`text-2xl font-black ${((order.totalAmount || 0) - (order.amountPaid || 0)) > 0.01 ? 'text-destructive' : 'text-primary'}`}>
              {formatCurrency(Math.max(0, (order.totalAmount || 0) - (order.amountPaid || 0)))}
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Order Notes -->
    {#if order.notes}
      <div class="bg-warning/10 p-5 rounded-2xl border-2 border-warning/30 text-warning-foreground shadow-sm">
        <h3 class="font-bold mb-2 text-sm uppercase tracking-wider opacity-80 flex items-center gap-2">Notas Generales</h3>
        <p class="text-base font-medium">{order.notes}</p>
      </div>
    {/if}

    <!-- Items -->
    <div class="bg-card border border-border rounded-2xl overflow-hidden shadow-sm">
      <div class="px-6 py-4 border-b border-border font-bold text-lg bg-secondary/20">Prendas y Servicios</div>
      <div class="overflow-x-auto">
        <Table.Root class="w-full text-sm text-left">
          <Table.Header class="bg-muted/30 text-muted-foreground uppercase text-xs font-bold">
            <Table.Row class="hover:bg-transparent">
              <Table.Head class="px-6 py-4 font-bold h-auto">Descripción</Table.Head>
              <Table.Head class="px-6 py-4 font-bold h-auto">Servicio</Table.Head>
              <Table.Head class="px-6 py-4 font-bold h-auto text-center">Cant</Table.Head>
              <Table.Head class="px-6 py-4 font-bold h-auto">Precio</Table.Head>
              <Table.Head class="px-6 py-4 font-bold h-auto text-right">Subtotal</Table.Head>
            </Table.Row>
          </Table.Header>
          <Table.Body class="divide-y divide-border">
            {#each order.items as item}
              <Table.Row class="hover:bg-muted/10 transition-colors">
                <Table.Cell class="px-6 py-4 align-top">
                  <div class="font-bold text-base">{item.garmentName}</div>
                  {#if item.notes}
                    <div class="text-sm text-muted-foreground mt-2 bg-warning/10 text-warning-foreground p-2 rounded-lg border border-warning/20 inline-block">
                      <span class="font-bold mr-1">Nota:</span>{item.notes}
                    </div>
                  {/if}
                </Table.Cell>
                <Table.Cell colspan={3} class="px-0 py-0 align-top">
                  <Table.Root class="w-full">
                    <Table.Body class="divide-y divide-border/20">
                      {#each item.services as service}
                        <Table.Row class="hover:bg-transparent border-0">
                          <Table.Cell class="px-6 py-3 w-1/3 text-muted-foreground font-medium">{service.serviceName}</Table.Cell>
                          <Table.Cell class="px-6 py-3 w-1/3 text-center font-mono bg-secondary/10">{item.quantity}</Table.Cell>
                          <Table.Cell class="px-6 py-3 w-1/3">
                            <div class="font-mono text-foreground">${service.unitPrice}</div>
                            {#if service.adjustmentAmount && service.adjustmentAmount !== 0}
                              <div class={`text-xs mt-1 font-mono font-bold ${service.adjustmentAmount > 0 ? 'text-destructive bg-destructive/10' : 'text-success bg-success/10'} px-2 py-0.5 rounded-md inline-block`}>
                                {service.adjustmentAmount > 0 ? '+' : ''}{service.adjustmentAmount}
                                {service.adjustmentReason && ` (${service.adjustmentReason})`}
                              </div>
                            {/if}
                          </Table.Cell>
                        </Table.Row>
                      {/each}
                    </Table.Body>
                  </Table.Root>
                </Table.Cell>
                <Table.Cell class="px-6 py-4 font-bold text-lg font-mono align-top text-right text-primary">${item.subtotal}</Table.Cell>
              </Table.Row>
            {/each}
          </Table.Body>
        </Table.Root>
      </div>
    </div>

    <!-- Actions -->
    <div class="flex flex-col sm:flex-row justify-between gap-4 pt-6 border-t border-border mt-8">
      <Button
        onclick={handleCancel}
        variant="ghost"
        class="text-destructive hover:bg-destructive-muted hover:text-destructive h-14 rounded-xl text-lg touch-manipulation w-full sm:w-auto"
      >
        Cancelar Pedido
      </Button>

      <div class="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
        {#if order.status === 'RECEIVED'}
          <Button
            onclick={handleSendToOps}
            class="h-14 rounded-xl text-lg touch-manipulation shadow-md w-full sm:w-auto"
          >
            Enviar a Operaciones
          </Button>
        {/if}
        <Button
          onclick={handlePrint}
          variant="outline"
          class="h-14 rounded-xl text-lg touch-manipulation shadow-sm border-2 w-full sm:w-auto"
        >
          Imprimir Ticket
        </Button>
      </div>
    </div>
  </div>
{/if}
